import { NextResponse } from 'next/server'
import { db } from '@/lib/db/client'

const CATALOG = [
  // ── Su ────────────────────────────────────────────────────────────────────────
  {
    drinkType: 'water_still',
    nametr: 'Doğal Su',
    nameen: 'Still Water',
    category: 'water',
    hydrationValue: 1.0,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'water-outline',
    color: '#32ADE6',
    descriptiontr:
      'En saf hidrasyon kaynağı. Vücudun her hücresine ulaşır, hiçbir şey suyu yetemez.',
  },
  {
    drinkType: 'water_sparkling',
    nametr: 'Maden Suyu',
    nameen: 'Sparkling Water',
    category: 'water',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'water',
    color: '#5AC8FA',
    descriptiontr: 'Gazsız suya yakın hidrasyon, fazladan karbondioksit eşliğinde.',
  },
  {
    drinkType: 'water_coconut',
    nametr: 'Hindistan Cevizi Suyu',
    nameen: 'Coconut Water',
    category: 'water',
    hydrationValue: 0.95,
    caffeinePerServing: 0,
    sugarPerServing: 6,
    defaultServingMl: 300,
    iconName: 'leaf-outline',
    color: '#30D158',
    descriptiontr:
      'Elektrolit zengini doğal içecek. Antrenman sonrası kas kramplarına karşı etkili.',
  },
  {
    drinkType: 'water_alkaline',
    nametr: 'Alkali Su',
    nameen: 'Alkaline Water',
    category: 'water',
    hydrationValue: 1.0,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'water-outline',
    color: '#0A84FF',
    descriptiontr: "Yüksek pH'lı su. Asit reflüsü şikayetleri olanlarda rahatlama sağlayabilir.",
  },
  {
    drinkType: 'water_infused',
    nametr: 'Meyveli Detoks Suyu',
    nameen: 'Infused Water',
    category: 'water',
    hydrationValue: 0.99,
    caffeinePerServing: 0,
    sugarPerServing: 1,
    defaultServingMl: 500,
    iconName: 'leaf',
    color: '#34C759',
    descriptiontr: 'Meyve, sebze veya bitki eklenmiş su. Lezzetli hidrasyon alternatifi.',
  },
  {
    drinkType: 'water_electrolyte',
    nametr: 'Elektrolit Suyu',
    nameen: 'Electrolyte Water',
    category: 'water',
    hydrationValue: 1.0,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 500,
    iconName: 'flash-outline',
    color: '#32ADE6',
    descriptiontr: 'Mineral takviyeli su. Yoğun ter kayıplarından sonra hızlı toparlanma.',
  },

  // ── Çay ───────────────────────────────────────────────────────────────────────
  {
    drinkType: 'tea_black',
    nametr: 'Siyah Çay',
    nameen: 'Black Tea',
    category: 'tea',
    hydrationValue: 0.85,
    caffeinePerServing: 47,
    sugarPerServing: 0,
    defaultServingMl: 200,
    iconName: 'cafe-outline',
    color: '#A2845E',
    descriptiontr: 'Türk kültürünün vazgeçilmezi. Antioksidan yönünden zengin, ama kafeine dikkat.',
  },
  {
    drinkType: 'tea_green',
    nametr: 'Yeşil Çay',
    nameen: 'Green Tea',
    category: 'tea',
    hydrationValue: 0.9,
    caffeinePerServing: 28,
    sugarPerServing: 0,
    defaultServingMl: 200,
    iconName: 'leaf',
    color: '#30D158',
    descriptiontr: 'Metabolizmayı hızlandıran polifenoller içerir. Günde 2-3 bardak ideal.',
  },
  {
    drinkType: 'tea_white',
    nametr: 'Beyaz Çay',
    nameen: 'White Tea',
    category: 'tea',
    hydrationValue: 0.92,
    caffeinePerServing: 15,
    sugarPerServing: 0,
    defaultServingMl: 200,
    iconName: 'flower-outline',
    color: '#F9F9FB',
    descriptiontr: 'En az işlenmiş çay. Antioksidan kapasitesi yüksek, kafein düşük.',
  },
  {
    drinkType: 'tea_oolong',
    nametr: 'Oolong Çay',
    nameen: 'Oolong Tea',
    category: 'tea',
    hydrationValue: 0.88,
    caffeinePerServing: 37,
    sugarPerServing: 0,
    defaultServingMl: 200,
    iconName: 'color-filter-outline',
    color: '#FF9F0A',
    descriptiontr: 'Yeşil ve siyah çay arasında. Yağ yakımını destekleyen bileşenler içerir.',
  },
  {
    drinkType: 'tea_matcha',
    nametr: 'Matcha',
    nameen: 'Matcha',
    category: 'tea',
    hydrationValue: 0.88,
    caffeinePerServing: 70,
    sugarPerServing: 0,
    defaultServingMl: 150,
    iconName: 'leaf',
    color: '#34C759',
    descriptiontr: 'L-Theanin + kafein kombinasyonu odaklanmayı artırır. Sakin ama uyanık hissi.',
  },
  {
    drinkType: 'tea_rooibos',
    nametr: 'Rooibos Çay',
    nameen: 'Rooibos Tea',
    category: 'tea',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flower-outline',
    color: '#FF6B35',
    descriptiontr: 'Kafeinsiz Güney Afrika çayı. Antioksidan zengini, uyku öncesi güvenli.',
  },
  {
    drinkType: 'tea_yerba_mate',
    nametr: 'Yerba Mate',
    nameen: 'Yerba Mate',
    category: 'tea',
    hydrationValue: 0.8,
    caffeinePerServing: 80,
    sugarPerServing: 0,
    defaultServingMl: 300,
    iconName: 'cafe-outline',
    color: '#8CD64A',
    descriptiontr: "Güney Amerika'nın enerji içeceği. Kafein + antioksidan, kahveden daha yumuşak.",
  },
  {
    drinkType: 'tea_turmeric',
    nametr: 'Zerdeçal Çayı',
    nameen: 'Turmeric Tea',
    category: 'tea',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flame-outline',
    color: '#FF9F0A',
    descriptiontr: 'Kurkumin güçlü anti-inflamatuar. Eklem ağrısı ve toparlanma için değerli.',
  },

  // ── Kahve ─────────────────────────────────────────────────────────────────────
  {
    drinkType: 'coffee_espresso',
    nametr: 'Espresso',
    nameen: 'Espresso',
    category: 'coffee',
    hydrationValue: 0.7,
    caffeinePerServing: 63,
    sugarPerServing: 0,
    defaultServingMl: 30,
    iconName: 'cafe',
    color: '#6F4E37',
    descriptiontr: 'Yoğun ve hızlı. Performansı artırır ama fazlası uyku kalitesini düşürür.',
  },
  {
    drinkType: 'coffee_filter',
    nametr: 'Filtre Kahve',
    nameen: 'Filter Coffee',
    category: 'coffee',
    hydrationValue: 0.72,
    caffeinePerServing: 95,
    sugarPerServing: 0,
    defaultServingMl: 240,
    iconName: 'cafe-outline',
    color: '#8B5E3C',
    descriptiontr: 'Yavaş demlenen, derin aromalar. Sabah rutini için mükemmel.',
  },
  {
    drinkType: 'coffee_latte',
    nametr: 'Latte',
    nameen: 'Latte',
    category: 'coffee',
    hydrationValue: 0.75,
    caffeinePerServing: 75,
    sugarPerServing: 10,
    defaultServingMl: 350,
    iconName: 'cafe',
    color: '#C4A882',
    descriptiontr: 'Süt bazlı, yumuşak kahve. Protein katkısı var ama kalori farkına dikkat.',
  },
  {
    drinkType: 'coffee_americano',
    nametr: 'Americano',
    nameen: 'Americano',
    category: 'coffee',
    hydrationValue: 0.8,
    caffeinePerServing: 63,
    sugarPerServing: 0,
    defaultServingMl: 240,
    iconName: 'cafe-outline',
    color: '#6F4E37',
    descriptiontr: 'Espresso + sıcak su. Filtre kahveye yakın yoğunluk, daha temiz profil.',
  },
  {
    drinkType: 'coffee_cappuccino',
    nametr: 'Cappuccino',
    nameen: 'Cappuccino',
    category: 'coffee',
    hydrationValue: 0.73,
    caffeinePerServing: 75,
    sugarPerServing: 5,
    defaultServingMl: 180,
    iconName: 'cafe',
    color: '#C4A882',
    descriptiontr: 'Espresso, buharlanmış süt ve köpük. Dengeli güç ve lezzet.',
  },
  {
    drinkType: 'coffee_cold_brew',
    nametr: 'Cold Brew',
    nameen: 'Cold Brew',
    category: 'coffee',
    hydrationValue: 0.78,
    caffeinePerServing: 155,
    sugarPerServing: 0,
    defaultServingMl: 300,
    iconName: 'snow-outline',
    color: '#5AC8FA',
    descriptiontr: 'Soğuk demlenmiş, yüksek kafeinli. Mide dostu asit profili, yavaş salınım.',
  },
  {
    drinkType: 'coffee_turkish',
    nametr: 'Türk Kahvesi',
    nameen: 'Turkish Coffee',
    category: 'coffee',
    hydrationValue: 0.68,
    caffeinePerServing: 50,
    sugarPerServing: 0,
    defaultServingMl: 60,
    iconName: 'cafe',
    color: '#3E1F00',
    descriptiontr: 'Köklü gelenek, yoğun aroma. Küçük fincan, büyük etki.',
  },
  {
    drinkType: 'coffee_macchiato',
    nametr: 'Macchiato',
    nameen: 'Macchiato',
    category: 'coffee',
    hydrationValue: 0.71,
    caffeinePerServing: 63,
    sugarPerServing: 3,
    defaultServingMl: 60,
    iconName: 'cafe-outline',
    color: '#A2845E',
    descriptiontr: 'Espresso üstüne az köpük. Sütün yumuşatıcılığıyla güçlü kafein.',
  },

  // ── Bitki Çayı ────────────────────────────────────────────────────────────────
  {
    drinkType: 'herbal_chamomile',
    nametr: 'Papatya Çayı',
    nameen: 'Chamomile Tea',
    category: 'herbal',
    hydrationValue: 0.98,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flower',
    color: '#FFD60A',
    descriptiontr: 'Kafeinsiz, sakinleştirici. Uyumadan önce içildiğinde uyku kalitesini artırır.',
  },
  {
    drinkType: 'herbal_ginger',
    nametr: 'Zencefil Çayı',
    nameen: 'Ginger Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flame-outline',
    color: '#FF6B35',
    descriptiontr: 'Anti-inflamatuar güçlü. Sindirime yardımcı, mide bulantısını geçirir.',
  },
  {
    drinkType: 'herbal_mint',
    nametr: 'Nane-Limon',
    nameen: 'Mint Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'leaf',
    color: '#34C759',
    descriptiontr: 'Ferahlatıcı ve sindirimi kolaylaştırıcı. Yemek sonrası için birebir.',
  },
  {
    drinkType: 'herbal_rosehip',
    nametr: 'Kuşburnu Çayı',
    nameen: 'Rosehip Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'heart-outline',
    color: '#FF2D55',
    descriptiontr: 'C vitamini deposu. Bağışıklık sistemini destekler, eklemlere iyi gelir.',
  },
  {
    drinkType: 'herbal_echinacea',
    nametr: 'Ekinezya Çayı',
    nameen: 'Echinacea Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'shield-outline',
    color: '#5E5CE6',
    descriptiontr: 'Bağışıklık güçlendirici. Özellikle hastalık dönemlerinde etkili.',
  },
  {
    drinkType: 'herbal_melissa',
    nametr: 'Melisa Çayı',
    nameen: 'Lemon Balm Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flower-outline',
    color: '#8CD64A',
    descriptiontr:
      'Stresi azaltan, sakinleştirici. Anksiyete ve sinirlilik hissine karşı doğal çözüm.',
  },
  {
    drinkType: 'herbal_lavender',
    nametr: 'Lavanta Çayı',
    nameen: 'Lavender Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flower',
    color: '#BF5AF2',
    descriptiontr: 'Gevşetici ve uyku düzenleyici. Gece ritüeli için ideal.',
  },
  {
    drinkType: 'herbal_hibiscus',
    nametr: 'Hibiskus Çayı',
    nameen: 'Hibiscus Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flower',
    color: '#FF2D55',
    descriptiontr: 'Kan basıncını düşürücü etki. C vitamini zengini, ekşi-meyveli tat.',
  },
  {
    drinkType: 'herbal_sage',
    nametr: 'Adaçayı',
    nameen: 'Sage Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'leaf-outline',
    color: '#34C759',
    descriptiontr: 'Boğaz enfeksiyonlarına karşı güçlü. Hafıza ve konsantrasyonu destekler.',
  },
  {
    drinkType: 'herbal_fennel',
    nametr: 'Rezene Çayı',
    nameen: 'Fennel Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'leaf',
    color: '#8CD64A',
    descriptiontr: 'Şişkinlik ve gaz giderici. Yemek sonrası sindirim desteği için mükemmel.',
  },

  // ── Meyve Suyu ────────────────────────────────────────────────────────────────
  {
    drinkType: 'juice_orange',
    nametr: 'Portakal Suyu',
    nameen: 'Orange Juice',
    category: 'juice',
    hydrationValue: 0.85,
    caffeinePerServing: 0,
    sugarPerServing: 26,
    defaultServingMl: 250,
    iconName: 'nutrition-outline',
    color: '#FF9F0A',
    descriptiontr: 'C vitamini zengini ama yüksek şeker içeriğine dikkat. Taze sıkılmış tercih et.',
  },
  {
    drinkType: 'juice_pomegranate',
    nametr: 'Nar Suyu',
    nameen: 'Pomegranate Juice',
    category: 'juice',
    hydrationValue: 0.83,
    caffeinePerServing: 0,
    sugarPerServing: 31,
    defaultServingMl: 250,
    iconName: 'nutrition',
    color: '#FF2D55',
    descriptiontr: 'Antioksidan şampiyonu. Kalp sağlığı ve toparlanma için değerli.',
  },
  {
    drinkType: 'juice_beet',
    nametr: 'Pancar Suyu',
    nameen: 'Beet Juice',
    category: 'juice',
    hydrationValue: 0.87,
    caffeinePerServing: 0,
    sugarPerServing: 14,
    defaultServingMl: 200,
    iconName: 'pulse-outline',
    color: '#BF5AF2',
    descriptiontr: 'Nitrat zengini. Antrenman performansını artırdığı bilimsel olarak kanıtlanmış.',
  },
  {
    drinkType: 'juice_apple',
    nametr: 'Elma Suyu',
    nameen: 'Apple Juice',
    category: 'juice',
    hydrationValue: 0.86,
    caffeinePerServing: 0,
    sugarPerServing: 28,
    defaultServingMl: 250,
    iconName: 'nutrition-outline',
    color: '#34C759',
    descriptiontr: 'Hafif meyveli lezzet. Elma pektin içerir, bağırsak sağlığına destek.',
  },
  {
    drinkType: 'juice_grape',
    nametr: 'Üzüm Suyu',
    nameen: 'Grape Juice',
    category: 'juice',
    hydrationValue: 0.82,
    caffeinePerServing: 0,
    sugarPerServing: 36,
    defaultServingMl: 250,
    iconName: 'nutrition',
    color: '#BF5AF2',
    descriptiontr: 'Resveratrol kaynağı. Yüksek şeker içerdiğinden porsiyon kontrolü önemli.',
  },
  {
    drinkType: 'juice_tomato',
    nametr: 'Domates Suyu',
    nameen: 'Tomato Juice',
    category: 'juice',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 6,
    defaultServingMl: 250,
    iconName: 'nutrition-outline',
    color: '#FF3B30',
    descriptiontr: 'Düşük kalorili, likopen zengini. Tuz içeriğine dikkat edin.',
  },
  {
    drinkType: 'juice_lemon',
    nametr: 'Limonata',
    nameen: 'Lemonade',
    category: 'juice',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 8,
    defaultServingMl: 300,
    iconName: 'sunny-outline',
    color: '#FFD60A',
    descriptiontr: 'Taze sıkılmış limon suyu + su. Detoks etkisi ve C vitamini desteği.',
  },
  {
    drinkType: 'juice_mixed',
    nametr: 'Karışık Meyve Suyu',
    nameen: 'Mixed Fruit Juice',
    category: 'juice',
    hydrationValue: 0.84,
    caffeinePerServing: 0,
    sugarPerServing: 24,
    defaultServingMl: 250,
    iconName: 'nutrition',
    color: '#FF9F0A',
    descriptiontr: 'Çoklu meyve karışımı, geniş vitamin profili. Şeker miktarını kontrol edin.',
  },

  // ── Spor İçeceği ─────────────────────────────────────────────────────────────
  {
    drinkType: 'sports_isotonic',
    nametr: 'İzotonik İçecek',
    nameen: 'Isotonic Drink',
    category: 'sports',
    hydrationValue: 0.92,
    caffeinePerServing: 0,
    sugarPerServing: 21,
    defaultServingMl: 500,
    iconName: 'flash-outline',
    color: '#0A84FF',
    descriptiontr: 'Elektrolit dengesini hızlı yeniler. Saatlik egzersiz sonrasında faydalı.',
  },
  {
    drinkType: 'sports_bcaa',
    nametr: 'BCAA İçeceği',
    nameen: 'BCAA Drink',
    category: 'sports',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 3,
    defaultServingMl: 500,
    iconName: 'barbell-outline',
    color: '#5E5CE6',
    descriptiontr:
      'Kas yıkımını önler, toparlanmayı hızlandırır. Antrenman sırasında veya sonrasında.',
  },
  {
    drinkType: 'sports_energy',
    nametr: 'Enerji İçeceği',
    nameen: 'Energy Drink',
    category: 'sports',
    hydrationValue: 0.6,
    caffeinePerServing: 160,
    sugarPerServing: 27,
    defaultServingMl: 250,
    iconName: 'battery-charging',
    color: '#FF3B30',
    descriptiontr: 'Yüksek kafein ve şeker. Kısa vadeli enerji, uzun vadede olumsuz etkiler.',
  },
  {
    drinkType: 'sports_protein',
    nametr: 'Protein Shake',
    nameen: 'Protein Shake',
    category: 'sports',
    hydrationValue: 0.85,
    caffeinePerServing: 0,
    sugarPerServing: 5,
    defaultServingMl: 400,
    iconName: 'barbell-outline',
    color: '#5E5CE6',
    descriptiontr: 'Antrenman sonrası kas onarımı için ideal. Whey veya bitki bazlı seçenekler.',
  },
  {
    drinkType: 'sports_preworkout',
    nametr: 'Pre-Workout',
    nameen: 'Pre-Workout',
    category: 'sports',
    hydrationValue: 0.75,
    caffeinePerServing: 200,
    sugarPerServing: 2,
    defaultServingMl: 300,
    iconName: 'flash',
    color: '#FF9F0A',
    descriptiontr: 'Yoğun kafein ve beta-alanin karışımı. Antrenman 30dk öncesi, miktara dikkat.',
  },
  {
    drinkType: 'sports_creatine',
    nametr: 'Kreatin İçeceği',
    nameen: 'Creatine Drink',
    category: 'sports',
    hydrationValue: 0.88,
    caffeinePerServing: 0,
    sugarPerServing: 1,
    defaultServingMl: 400,
    iconName: 'barbell-outline',
    color: '#30D158',
    descriptiontr: 'Güç ve kuvvet geliştirme için kanıtlanmış. Yükleme fazında bol su içilmeli.',
  },
  {
    drinkType: 'sports_hypotonic',
    nametr: 'Hipotonik İçecek',
    nameen: 'Hypotonic Drink',
    category: 'sports',
    hydrationValue: 0.95,
    caffeinePerServing: 0,
    sugarPerServing: 4,
    defaultServingMl: 500,
    iconName: 'flash-outline',
    color: '#32ADE6',
    descriptiontr: 'Düşük şeker, hızlı sıvı emilimi. Kısa süreli antrenmanlarda izotonikten üstün.',
  },

  // ── Süt & Protein ─────────────────────────────────────────────────────────────
  {
    drinkType: 'dairy_milk',
    nametr: 'Süt',
    nameen: 'Milk',
    category: 'dairy',
    hydrationValue: 0.87,
    caffeinePerServing: 0,
    sugarPerServing: 12,
    defaultServingMl: 250,
    iconName: 'nutrition-outline',
    color: '#F9F9FB',
    descriptiontr:
      'Protein, kalsiyum ve D vitamini kaynağı. Antrenman sonrası toparlanmada etkili.',
  },
  {
    drinkType: 'dairy_ayran',
    nametr: 'Ayran',
    nameen: 'Ayran',
    category: 'dairy',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 4,
    defaultServingMl: 250,
    iconName: 'water-outline',
    color: '#F2F2F7',
    descriptiontr: 'Probiyotik ve elektrolitler. Türk mutfağının geleneksel hidrasyon içeceği.',
  },
  {
    drinkType: 'dairy_kefir',
    nametr: 'Kefir',
    nameen: 'Kefir',
    category: 'dairy',
    hydrationValue: 0.85,
    caffeinePerServing: 0,
    sugarPerServing: 8,
    defaultServingMl: 200,
    iconName: 'shield-outline',
    color: '#F9F9FB',
    descriptiontr: 'Probiyotik şampiyonu. Bağırsak florasını güçlendirir, bağışıklığı destekler.',
  },
  {
    drinkType: 'dairy_oat_milk',
    nametr: 'Yulaf Sütü',
    nameen: 'Oat Milk',
    category: 'dairy',
    hydrationValue: 0.88,
    caffeinePerServing: 0,
    sugarPerServing: 7,
    defaultServingMl: 250,
    iconName: 'leaf-outline',
    color: '#C4A882',
    descriptiontr: 'Beta-glukan içerir. Kolesterol düşürücü etki, hafif ve sindirimi kolay.',
  },
  {
    drinkType: 'dairy_soy_milk',
    nametr: 'Soya Sütü',
    nameen: 'Soy Milk',
    category: 'dairy',
    hydrationValue: 0.87,
    caffeinePerServing: 0,
    sugarPerServing: 6,
    defaultServingMl: 250,
    iconName: 'leaf',
    color: '#8CD64A',
    descriptiontr: 'Bitkisel protein kaynağı. Laktozu tolere edemeyenler için ideal alternatif.',
  },
  {
    drinkType: 'dairy_almond_milk',
    nametr: 'Badem Sütü',
    nameen: 'Almond Milk',
    category: 'dairy',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 3,
    defaultServingMl: 250,
    iconName: 'leaf-outline',
    color: '#C4A882',
    descriptiontr:
      'Düşük kalori, E vitamini zengini. Bitkisel tercih arayanlar için hafif seçenek.',
  },

  // ── Smoothie & Detoks ─────────────────────────────────────────────────────────
  {
    drinkType: 'smoothie_green',
    nametr: 'Yeşil Detoks Smoothie',
    nameen: 'Green Detox Smoothie',
    category: 'smoothie',
    hydrationValue: 0.85,
    caffeinePerServing: 0,
    sugarPerServing: 12,
    defaultServingMl: 350,
    iconName: 'leaf',
    color: '#30D158',
    descriptiontr: 'Ispanak, salatalık, elma karışımı. Sindirim sistemi ve cilt için güçlü destek.',
  },
  {
    drinkType: 'smoothie_berry',
    nametr: 'Meyveli Smoothie',
    nameen: 'Berry Smoothie',
    category: 'smoothie',
    hydrationValue: 0.83,
    caffeinePerServing: 0,
    sugarPerServing: 18,
    defaultServingMl: 350,
    iconName: 'nutrition',
    color: '#FF2D55',
    descriptiontr: 'Çilek, yaban mersini, ahududu karışımı. Antioksidan ve lif açısından zengin.',
  },
  {
    drinkType: 'smoothie_banana',
    nametr: 'Muz Smoothie',
    nameen: 'Banana Smoothie',
    category: 'smoothie',
    hydrationValue: 0.82,
    caffeinePerServing: 0,
    sugarPerServing: 20,
    defaultServingMl: 350,
    iconName: 'nutrition-outline',
    color: '#FFD60A',
    descriptiontr: 'Potasyum ve magnezyum zengini. Antrenman öncesi hızlı enerji kaynağı.',
  },
  {
    drinkType: 'smoothie_acai',
    nametr: 'Açai Smoothie',
    nameen: 'Acai Smoothie',
    category: 'smoothie',
    hydrationValue: 0.8,
    caffeinePerServing: 0,
    sugarPerServing: 10,
    defaultServingMl: 300,
    iconName: 'nutrition',
    color: '#BF5AF2',
    descriptiontr: 'Süper meyve açai. Omega yağları ve antioksidanlar, sporcu toparlanması için.',
  },
  {
    drinkType: 'smoothie_collagen',
    nametr: 'Kolajen İçeceği',
    nameen: 'Collagen Drink',
    category: 'smoothie',
    hydrationValue: 0.88,
    caffeinePerServing: 0,
    sugarPerServing: 5,
    defaultServingMl: 300,
    iconName: 'sparkles-outline',
    color: '#FF9F0A',
    descriptiontr:
      'Cilt elastikiyeti ve eklem sağlığı için. Hidrolize kolajen en iyi emilim sağlar.',
  },

  // ── Gazlı ─────────────────────────────────────────────────────────────────────
  {
    drinkType: 'soda_cola',
    nametr: 'Kola',
    nameen: 'Cola',
    category: 'soda',
    hydrationValue: 0.5,
    caffeinePerServing: 34,
    sugarPerServing: 39,
    defaultServingMl: 330,
    iconName: 'warning-outline',
    color: '#8B0000',
    descriptiontr:
      'Yüksek şeker, düşük besin değeri. Zaman zaman keyif için olur ama alışkanlık yapma.',
  },
  {
    drinkType: 'soda_diet',
    nametr: 'Light/Diyet Gazlı',
    nameen: 'Diet Soda',
    category: 'soda',
    hydrationValue: 0.6,
    caffeinePerServing: 46,
    sugarPerServing: 0,
    defaultServingMl: 330,
    iconName: 'alert-circle-outline',
    color: '#FF6B35',
    descriptiontr: 'Şekersiz ama yapay tatlandırıcılar bağırsak florasını etkileyebilir.',
  },
  {
    drinkType: 'soda_soda_water',
    nametr: 'Soda',
    nameen: 'Club Soda',
    category: 'soda',
    hydrationValue: 0.95,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'water',
    color: '#5AC8FA',
    descriptiontr: 'Şekersiz, kafeinsiz. Gazlı su alternatifi olarak güvenli.',
  },
  {
    drinkType: 'soda_tonic',
    nametr: 'Tonik Su',
    nameen: 'Tonic Water',
    category: 'soda',
    hydrationValue: 0.7,
    caffeinePerServing: 0,
    sugarPerServing: 22,
    defaultServingMl: 250,
    iconName: 'water-outline',
    color: '#5AC8FA',
    descriptiontr: 'Kinin içerir, acımsı tat. Orta düzeyde şeker, spor sonrası önerilmez.',
  },
  {
    drinkType: 'soda_ginger_ale',
    nametr: 'Zencefilli Gazoz',
    nameen: 'Ginger Ale',
    category: 'soda',
    hydrationValue: 0.65,
    caffeinePerServing: 0,
    sugarPerServing: 26,
    defaultServingMl: 330,
    iconName: 'flame-outline',
    color: '#FF9F0A',
    descriptiontr: 'Zencefil aromalı gazoz. Mide bulantısında hafif rahatlama sağlayabilir.',
  },
  {
    drinkType: 'soda_kombucha',
    nametr: 'Kombucha',
    nameen: 'Kombucha',
    category: 'soda',
    hydrationValue: 0.8,
    caffeinePerServing: 15,
    sugarPerServing: 6,
    defaultServingMl: 330,
    iconName: 'leaf-outline',
    color: '#8CD64A',
    descriptiontr:
      'Fermente çay, probiyotik zengini. Bağırsak sağlığı için gazlılar arasında en iyi.',
  },
  {
    drinkType: 'soda_orange',
    nametr: 'Portakallı Gazoz',
    nameen: 'Orange Soda',
    category: 'soda',
    hydrationValue: 0.55,
    caffeinePerServing: 0,
    sugarPerServing: 35,
    defaultServingMl: 330,
    iconName: 'warning-outline',
    color: '#FF9F0A',
    descriptiontr: 'Yüksek şeker, düşük besin değeri. Occasional treat olarak sınırlı tüketilmeli.',
  },
  {
    drinkType: 'soda_lemon',
    nametr: 'Limonlu Gazoz',
    nameen: 'Lemon Soda',
    category: 'soda',
    hydrationValue: 0.6,
    caffeinePerServing: 0,
    sugarPerServing: 30,
    defaultServingMl: 330,
    iconName: 'alert-circle-outline',
    color: '#FFD60A',
    descriptiontr: 'Ferahlatıcı ama yüksek şekerli. Limonata ile karıştırılmamalı.',
  },
  {
    drinkType: 'soda_sparkling_juice',
    nametr: 'Gazlı Meyve Suyu',
    nameen: 'Sparkling Juice',
    category: 'soda',
    hydrationValue: 0.75,
    caffeinePerServing: 0,
    sugarPerServing: 20,
    defaultServingMl: 250,
    iconName: 'nutrition-outline',
    color: '#34C759',
    descriptiontr: 'Gerçek meyve suyu + gaz. Gazlı içecek isteyenler için görece daha iyi seçenek.',
  },
  {
    drinkType: 'soda_water_kefir',
    nametr: 'Su Kefiri',
    nameen: 'Water Kefir',
    category: 'soda',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 4,
    defaultServingMl: 250,
    iconName: 'shield-outline',
    color: '#30D158',
    descriptiontr: 'Fermente, probiyotik gazlı içecek. Bağırsak sağlığı için gazlıların en iyisi.',
  },

  // ── Su (ek) ───────────────────────────────────────────────────────────────────
  {
    drinkType: 'water_hydrogen',
    nametr: 'Hidrojen Suyu',
    nameen: 'Hydrogen Water',
    category: 'water',
    hydrationValue: 1.0,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'water-outline',
    color: '#0A84FF',
    descriptiontr: 'Moleküler hidrojen eklenmiş su. Antioksidan etkisi araştırılıyor, güvenli.',
  },
  {
    drinkType: 'water_mineral',
    nametr: 'Mineral Su',
    nameen: 'Mineral Water',
    category: 'water',
    hydrationValue: 0.99,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'water',
    color: '#5AC8FA',
    descriptiontr:
      'Doğal mineraller içerir. Kalsiyum ve magnezyum kemik ve kas sağlığına katkı sağlar.',
  },
  {
    drinkType: 'water_vitamin',
    nametr: 'Vitaminli Su',
    nameen: 'Vitamin Water',
    category: 'water',
    hydrationValue: 0.95,
    caffeinePerServing: 0,
    sugarPerServing: 13,
    defaultServingMl: 500,
    iconName: 'flash-outline',
    color: '#FFD60A',
    descriptiontr:
      'Vitamin takviyeli su. Şeker içeriğine dikkat; bazı markalar yüksek şeker kullanır.',
  },

  // ── Çay (ek) ──────────────────────────────────────────────────────────────────
  {
    drinkType: 'tea_chai',
    nametr: 'Chai Latte',
    nameen: 'Chai Latte',
    category: 'tea',
    hydrationValue: 0.82,
    caffeinePerServing: 50,
    sugarPerServing: 12,
    defaultServingMl: 300,
    iconName: 'cafe-outline',
    color: '#FF9F0A',
    descriptiontr: 'Baharatlı çay + süt. Tarçın, zencefil, kakule karışımı anti-inflamatuar etki.',
  },
  {
    drinkType: 'tea_butterfly_pea',
    nametr: 'Kelebek Bezelyesi Çayı',
    nameen: 'Butterfly Pea Tea',
    category: 'tea',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flower',
    color: '#5E5CE6',
    descriptiontr: 'Renk değiştiren egzotik çay. Antosiyanin zengini, kafeinsiz ve görsel şöleni.',
  },
  {
    drinkType: 'tea_sencha',
    nametr: 'Sencha',
    nameen: 'Sencha',
    category: 'tea',
    hydrationValue: 0.91,
    caffeinePerServing: 30,
    sugarPerServing: 0,
    defaultServingMl: 200,
    iconName: 'leaf',
    color: '#30D158',
    descriptiontr:
      "Japon yeşil çayı. Matcha'dan daha hafif, catechin zengini, günlük tüketim için ideal.",
  },
  {
    drinkType: 'tea_pu_erh',
    nametr: 'Pu-erh Çay',
    nameen: 'Pu-erh Tea',
    category: 'tea',
    hydrationValue: 0.86,
    caffeinePerServing: 60,
    sugarPerServing: 0,
    defaultServingMl: 200,
    iconName: 'cafe-outline',
    color: '#A2845E',
    descriptiontr:
      'Fermente Çin çayı. Kolesterol düşürücü etki, sindirim dostu, güçlü toprak aroması.',
  },
  {
    drinkType: 'tea_barley',
    nametr: 'Arpa Çayı',
    nameen: 'Barley Tea',
    category: 'tea',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'leaf-outline',
    color: '#C4A882',
    descriptiontr:
      "Kafeinsiz, hafif kavrulmuş arpa. Sindirime yardımcı, Kore ve Japonya'da yaygın.",
  },

  // ── Kahve (ek) ────────────────────────────────────────────────────────────────
  {
    drinkType: 'coffee_flat_white',
    nametr: 'Flat White',
    nameen: 'Flat White',
    category: 'coffee',
    hydrationValue: 0.74,
    caffeinePerServing: 130,
    sugarPerServing: 6,
    defaultServingMl: 180,
    iconName: 'cafe',
    color: '#C4A882',
    descriptiontr:
      "Yoğun espresso + az mikro köpük. Latte'ye göre daha güçlü, cappuccino'ya göre daha yumuşak.",
  },
  {
    drinkType: 'coffee_mocha',
    nametr: 'Mocha',
    nameen: 'Mocha',
    category: 'coffee',
    hydrationValue: 0.72,
    caffeinePerServing: 95,
    sugarPerServing: 22,
    defaultServingMl: 350,
    iconName: 'cafe-outline',
    color: '#6F4E37',
    descriptiontr: 'Espresso + çikolata + süt. Kafein ve şeker kombinasyonu, tadında bırak.',
  },
  {
    drinkType: 'coffee_ristretto',
    nametr: 'Ristretto',
    nameen: 'Ristretto',
    category: 'coffee',
    hydrationValue: 0.65,
    caffeinePerServing: 35,
    sugarPerServing: 0,
    defaultServingMl: 20,
    iconName: 'cafe',
    color: '#3E1F00',
    descriptiontr: "Espresso'dan bile kısa ve yoğun. Daha az kafein, daha konsantre aroma.",
  },
  {
    drinkType: 'coffee_lungo',
    nametr: 'Lungo',
    nameen: 'Lungo',
    category: 'coffee',
    hydrationValue: 0.77,
    caffeinePerServing: 77,
    sugarPerServing: 0,
    defaultServingMl: 120,
    iconName: 'cafe-outline',
    color: '#8B5E3C',
    descriptiontr: 'Uzun espresso. Daha fazla su, daha fazla kafein çıkarımı, biraz daha acı.',
  },
  {
    drinkType: 'coffee_nitro',
    nametr: 'Nitro Cold Brew',
    nameen: 'Nitro Cold Brew',
    category: 'coffee',
    hydrationValue: 0.78,
    caffeinePerServing: 215,
    sugarPerServing: 0,
    defaultServingMl: 300,
    iconName: 'snow-outline',
    color: '#0A84FF',
    descriptiontr: 'Azot gazıyla servis edilen cold brew. Kremsi doku, çok yüksek kafein içeriği.',
  },
  {
    drinkType: 'coffee_dalgona',
    nametr: 'Dalgona Kahve',
    nameen: 'Dalgona Coffee',
    category: 'coffee',
    hydrationValue: 0.73,
    caffeinePerServing: 80,
    sugarPerServing: 15,
    defaultServingMl: 300,
    iconName: 'cafe',
    color: '#C4A882',
    descriptiontr: 'Çırpılmış kahve köpüğü + soğuk süt. Popüler trend, şeker içeriğine dikkat.',
  },

  // ── Bitki Çayı (ek) ───────────────────────────────────────────────────────────
  {
    drinkType: 'herbal_linden',
    nametr: 'Ihlamur',
    nameen: 'Linden Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flower-outline',
    color: '#FFD60A',
    descriptiontr: 'Soğuk algınlığına karşı klasik. Ateş düşürücü ve rahatlatıcı etki.',
  },
  {
    drinkType: 'herbal_thyme',
    nametr: 'Kekik Çayı',
    nameen: 'Thyme Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'leaf',
    color: '#34C759',
    descriptiontr: 'Antimikrobiyal ve öksürük giderici. Solunum yolları için güçlü destek.',
  },
  {
    drinkType: 'herbal_cinnamon',
    nametr: 'Tarçın Çayı',
    nameen: 'Cinnamon Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flame-outline',
    color: '#A2845E',
    descriptiontr:
      'Kan şekerini dengelemeye yardımcı. Kış için ısıtıcı ve metabolizma destekleyici.',
  },
  {
    drinkType: 'herbal_nettle',
    nametr: 'Isırgan Otu Çayı',
    nameen: 'Nettle Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'leaf-outline',
    color: '#30D158',
    descriptiontr: 'Demir ve mineral deposu. Saç dökülmesi ve eklem sağlığı için geleneksel çözüm.',
  },
  {
    drinkType: 'herbal_valerian',
    nametr: 'Kediotu Çayı',
    nameen: 'Valerian Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'moon-outline',
    color: '#5E5CE6',
    descriptiontr: 'Doğal uyku yardımcısı. Güçlü sakinleştirici etki, gece dışında içilmemeli.',
  },
  {
    drinkType: 'herbal_elderflower',
    nametr: 'Mürver Çiçeği Çayı',
    nameen: 'Elderflower Tea',
    category: 'herbal',
    hydrationValue: 0.97,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'flower',
    color: '#F9F9FB',
    descriptiontr:
      'Antiviral ve bağışıklık güçlendirici. Gribal enfeksiyonlara karşı erken dönemde etkili.',
  },

  // ── Meyve Suyu (ek) ───────────────────────────────────────────────────────────
  {
    drinkType: 'juice_cherry',
    nametr: 'Vişne Suyu',
    nameen: 'Cherry Juice',
    category: 'juice',
    hydrationValue: 0.85,
    caffeinePerServing: 0,
    sugarPerServing: 22,
    defaultServingMl: 250,
    iconName: 'nutrition',
    color: '#FF2D55',
    descriptiontr: 'Melatonin içerir. Uyku kalitesini artırır, kas toparlanmasında etkili.',
  },
  {
    drinkType: 'juice_watermelon',
    nametr: 'Karpuz Suyu',
    nameen: 'Watermelon Juice',
    category: 'juice',
    hydrationValue: 0.92,
    caffeinePerServing: 0,
    sugarPerServing: 9,
    defaultServingMl: 300,
    iconName: 'nutrition-outline',
    color: '#FF3B30',
    descriptiontr:
      'L-Sitrülin içerir. Kas yorgunluğunu azaltır, yüksek su içeriğiyle üstün hidrasyon.',
  },
  {
    drinkType: 'juice_mango',
    nametr: 'Mango Suyu',
    nameen: 'Mango Juice',
    category: 'juice',
    hydrationValue: 0.83,
    caffeinePerServing: 0,
    sugarPerServing: 29,
    defaultServingMl: 250,
    iconName: 'nutrition',
    color: '#FF9F0A',
    descriptiontr:
      'Tropikal meyve, A ve C vitamini zengini. Yüksek şeker içeriğinden dolayı porsiyona dikkat.',
  },
  {
    drinkType: 'juice_pineapple',
    nametr: 'Ananas Suyu',
    nameen: 'Pineapple Juice',
    category: 'juice',
    hydrationValue: 0.86,
    caffeinePerServing: 0,
    sugarPerServing: 25,
    defaultServingMl: 250,
    iconName: 'nutrition-outline',
    color: '#FFD60A',
    descriptiontr:
      'Bromelain enzimi içerir. Sindirimi kolaylaştırır ve anti-inflamatuar etki gösterir.',
  },
  {
    drinkType: 'juice_celery',
    nametr: 'Kereviz Suyu',
    nameen: 'Celery Juice',
    category: 'juice',
    hydrationValue: 0.94,
    caffeinePerServing: 0,
    sugarPerServing: 4,
    defaultServingMl: 300,
    iconName: 'leaf',
    color: '#34C759',
    descriptiontr: 'Düşük kalorili, sodyum dengeli. Detoks trendi, böbrek sağlığı için faydalı.',
  },
  {
    drinkType: 'juice_grapefruit',
    nametr: 'Greyfurt Suyu',
    nameen: 'Grapefruit Juice',
    category: 'juice',
    hydrationValue: 0.88,
    caffeinePerServing: 0,
    sugarPerServing: 16,
    defaultServingMl: 250,
    iconName: 'nutrition-outline',
    color: '#FF6B35',
    descriptiontr: 'Metabolizmayı hızlandırır. Bazı ilaçlarla etkileşime girebilir, dikkat edin.',
  },

  // ── Spor İçeceği (ek) ────────────────────────────────────────────────────────
  {
    drinkType: 'sports_glutamine',
    nametr: 'Glutamin İçeceği',
    nameen: 'Glutamine Drink',
    category: 'sports',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 300,
    iconName: 'barbell-outline',
    color: '#30D158',
    descriptiontr:
      'Bağırsak sağlığı ve bağışıklık desteği. Yoğun antrenman sonrası toparlanmayı hızlandırır.',
  },
  {
    drinkType: 'sports_casein',
    nametr: 'Kazein Shake',
    nameen: 'Casein Shake',
    category: 'sports',
    hydrationValue: 0.83,
    caffeinePerServing: 0,
    sugarPerServing: 4,
    defaultServingMl: 350,
    iconName: 'moon-outline',
    color: '#5E5CE6',
    descriptiontr: 'Yavaş sindirim proteini. Uyku öncesi alındığında gece kas onarımını destekler.',
  },
  {
    drinkType: 'sports_recovery',
    nametr: 'Toparlanma İçeceği',
    nameen: 'Recovery Drink',
    category: 'sports',
    hydrationValue: 0.88,
    caffeinePerServing: 0,
    sugarPerServing: 15,
    defaultServingMl: 500,
    iconName: 'flash-outline',
    color: '#FF9F0A',
    descriptiontr:
      'Karbonhidrat + protein karışımı. Uzun antrenman sonrası glikojen depolarını yeniler.',
  },
  {
    drinkType: 'sports_collagen',
    nametr: 'Spor Kolajen İçeceği',
    nameen: 'Sport Collagen Drink',
    category: 'sports',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 3,
    defaultServingMl: 300,
    iconName: 'barbell-outline',
    color: '#FF6B35',
    descriptiontr:
      'Eklem ve bağ dokusu desteği. Yüksek darbe sporu yapanlarda sakatlanma riskini azaltır.',
  },

  // ── Süt & Protein (ek) ────────────────────────────────────────────────────────
  {
    drinkType: 'dairy_rice_milk',
    nametr: 'Pirinç Sütü',
    nameen: 'Rice Milk',
    category: 'dairy',
    hydrationValue: 0.89,
    caffeinePerServing: 0,
    sugarPerServing: 10,
    defaultServingMl: 250,
    iconName: 'leaf-outline',
    color: '#F9F9FB',
    descriptiontr: 'En az alerjenik süt alternatifi. Sindirim dostu, hafif ve tatlımsı.',
  },
  {
    drinkType: 'dairy_hemp_milk',
    nametr: 'Kenevir Sütü',
    nameen: 'Hemp Milk',
    category: 'dairy',
    hydrationValue: 0.88,
    caffeinePerServing: 0,
    sugarPerServing: 3,
    defaultServingMl: 250,
    iconName: 'leaf',
    color: '#8CD64A',
    descriptiontr:
      'Omega-3 ve omega-6 zengini. Tam protein kaynağı, beyin ve kalp sağlığı için değerli.',
  },
  {
    drinkType: 'dairy_chocolate_milk',
    nametr: 'Çikolatalı Süt',
    nameen: 'Chocolate Milk',
    category: 'dairy',
    hydrationValue: 0.84,
    caffeinePerServing: 5,
    sugarPerServing: 24,
    defaultServingMl: 250,
    iconName: 'nutrition',
    color: '#6F4E37',
    descriptiontr:
      'Protein + karbonhidrat. Antrenman sonrası toparlanma için bilimsel onaylı seçenek.',
  },
  {
    drinkType: 'dairy_coconut_milk',
    nametr: 'Hindistan Cevizi Sütü',
    nameen: 'Coconut Milk',
    category: 'dairy',
    hydrationValue: 0.82,
    caffeinePerServing: 0,
    sugarPerServing: 3,
    defaultServingMl: 250,
    iconName: 'leaf-outline',
    color: '#30D158',
    descriptiontr:
      'MCT yağları içerir. Hızlı enerji kaynağı, keto ve düşük karbonhidrat diyetleri için uygun.',
  },
  {
    drinkType: 'dairy_cashew_milk',
    nametr: 'Kaju Sütü',
    nameen: 'Cashew Milk',
    category: 'dairy',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 2,
    defaultServingMl: 250,
    iconName: 'leaf',
    color: '#C4A882',
    descriptiontr: 'Kremsi doku, düşük kalori. Magnezyum ve çinko içerir, bağışıklık destekleyici.',
  },

  // ── Smoothie (ek) ─────────────────────────────────────────────────────────────
  {
    drinkType: 'smoothie_spinach',
    nametr: 'Ispanak Smoothie',
    nameen: 'Spinach Smoothie',
    category: 'smoothie',
    hydrationValue: 0.87,
    caffeinePerServing: 0,
    sugarPerServing: 10,
    defaultServingMl: 350,
    iconName: 'leaf',
    color: '#30D158',
    descriptiontr: 'Demir ve folat zengini. Muz ile tatlandırılmış yeşil güç içeceği.',
  },
  {
    drinkType: 'smoothie_mango',
    nametr: 'Mango Lassi',
    nameen: 'Mango Lassi',
    category: 'smoothie',
    hydrationValue: 0.84,
    caffeinePerServing: 0,
    sugarPerServing: 22,
    defaultServingMl: 350,
    iconName: 'nutrition',
    color: '#FF9F0A',
    descriptiontr: 'Hint kökenli mango + yoğurt. Probiyotik ve A vitamini, sindirimi destekler.',
  },
  {
    drinkType: 'smoothie_peanut',
    nametr: 'Fıstık Ezmeli Smoothie',
    nameen: 'Peanut Butter Smoothie',
    category: 'smoothie',
    hydrationValue: 0.8,
    caffeinePerServing: 0,
    sugarPerServing: 14,
    defaultServingMl: 350,
    iconName: 'barbell-outline',
    color: '#C4A882',
    descriptiontr: 'Protein ve sağlıklı yağ kombinasyonu. Antrenman öncesi uzun süreli enerji.',
  },
  {
    drinkType: 'smoothie_tropical',
    nametr: 'Tropikal Smoothie',
    nameen: 'Tropical Smoothie',
    category: 'smoothie',
    hydrationValue: 0.85,
    caffeinePerServing: 0,
    sugarPerServing: 19,
    defaultServingMl: 400,
    iconName: 'sunny-outline',
    color: '#FFD60A',
    descriptiontr: 'Ananas, mango, hindistan cevizi karışımı. C vitamini ve sindirim enzimleri.',
  },
  {
    drinkType: 'smoothie_avocado',
    nametr: 'Avokado Smoothie',
    nameen: 'Avocado Smoothie',
    category: 'smoothie',
    hydrationValue: 0.82,
    caffeinePerServing: 0,
    sugarPerServing: 6,
    defaultServingMl: 300,
    iconName: 'leaf-outline',
    color: '#34C759',
    descriptiontr: 'Sağlıklı yağlar ve K vitamini. Doyurucu, kalp dostu, düşük şekerli tercih.',
  },
  {
    drinkType: 'smoothie_oat',
    nametr: 'Yulaf Smoothie',
    nameen: 'Oat Smoothie',
    category: 'smoothie',
    hydrationValue: 0.83,
    caffeinePerServing: 0,
    sugarPerServing: 12,
    defaultServingMl: 350,
    iconName: 'nutrition-outline',
    color: '#C4A882',
    descriptiontr: 'Beta-glukan ve lif zengini. Uzun süre tok tutar, kolesterol dengeleme etkisi.',
  },
  {
    drinkType: 'smoothie_ginger_lemon',
    nametr: 'Zencefil-Limon Shot',
    nameen: 'Ginger Lemon Shot',
    category: 'smoothie',
    hydrationValue: 0.9,
    caffeinePerServing: 0,
    sugarPerServing: 3,
    defaultServingMl: 60,
    iconName: 'flame-outline',
    color: '#FF6B35',
    descriptiontr: 'Konsantre bağışıklık bombası. Sabah aç karnına alındığında maksimum etki.',
  },

  // ── Kahve (ek) ────────────────────────────────────────────────────────────────
  {
    drinkType: 'coffee_affogato',
    nametr: 'Affogato',
    nameen: 'Affogato',
    category: 'coffee',
    hydrationValue: 0.6,
    caffeinePerServing: 63,
    sugarPerServing: 14,
    defaultServingMl: 150,
    iconName: 'cafe',
    color: '#6F4E37',
    descriptiontr: 'Espresso + dondurma. Sıcak-soğuk kontrast, dessert kahve; yüksek kalori.',
  },
  {
    drinkType: 'coffee_cortado',
    nametr: 'Cortado',
    nameen: 'Cortado',
    category: 'coffee',
    hydrationValue: 0.72,
    caffeinePerServing: 63,
    sugarPerServing: 3,
    defaultServingMl: 90,
    iconName: 'cafe-outline',
    color: '#A2845E',
    descriptiontr: 'Eşit ölçü espresso ve süt. Asiditeyi dengeleyen İspanyol klasiği.',
  },
  {
    drinkType: 'coffee_vienna',
    nametr: 'Viyana Kahvesi',
    nameen: 'Vienna Coffee',
    category: 'coffee',
    hydrationValue: 0.68,
    caffeinePerServing: 95,
    sugarPerServing: 8,
    defaultServingMl: 250,
    iconName: 'cafe',
    color: '#C4A882',
    descriptiontr: 'Filtre kahve üstüne çırpılmış krema. Zengin doku, yüksek kafein.',
  },
  {
    drinkType: 'coffee_irish',
    nametr: 'Irish Coffee',
    nameen: 'Irish Coffee',
    category: 'coffee',
    hydrationValue: 0.55,
    caffeinePerServing: 95,
    sugarPerServing: 6,
    defaultServingMl: 200,
    iconName: 'cafe-outline',
    color: '#8B5E3C',
    descriptiontr:
      'Kahve + viski + krema. Alkol ve kafein kombinasyonu; antrenman günleri önerilmez.',
  },
  {
    drinkType: 'coffee_greek_frappe',
    nametr: 'Yunan Frappé',
    nameen: 'Greek Frappé',
    category: 'coffee',
    hydrationValue: 0.7,
    caffeinePerServing: 75,
    sugarPerServing: 10,
    defaultServingMl: 300,
    iconName: 'snow-outline',
    color: '#5AC8FA',
    descriptiontr:
      'Köpüklü soğuk kahve klasiği. Yaz sezonunun vazgeçilmezi, şeker kontrolüne dikkat.',
  },
  {
    drinkType: 'coffee_vietnamese',
    nametr: 'Vietnam Kahvesi',
    nameen: 'Vietnamese Coffee',
    category: 'coffee',
    hydrationValue: 0.65,
    caffeinePerServing: 100,
    sugarPerServing: 20,
    defaultServingMl: 200,
    iconName: 'cafe',
    color: '#A2845E',
    descriptiontr: 'Yoğun robusta + yoğunlaştırılmış süt. Çok tatlı ve yüksek kafeinli.',
  },
  {
    drinkType: 'coffee_oat_latte',
    nametr: 'Yulaf Lattesi',
    nameen: 'Oat Latte',
    category: 'coffee',
    hydrationValue: 0.76,
    caffeinePerServing: 75,
    sugarPerServing: 9,
    defaultServingMl: 350,
    iconName: 'cafe-outline',
    color: '#C4A882',
    descriptiontr: 'Espresso + yulaf sütü. Bitkisel latte alternatifi, kolesterol dostu.',
  },
  {
    drinkType: 'coffee_bulletproof',
    nametr: 'Bulletproof Kahve',
    nameen: 'Bulletproof Coffee',
    category: 'coffee',
    hydrationValue: 0.65,
    caffeinePerServing: 95,
    sugarPerServing: 0,
    defaultServingMl: 350,
    iconName: 'flash',
    color: '#FF9F0A',
    descriptiontr: 'Kahve + tereyağı + MCT yağı. Keto diyeti için uzun süreli enerji ve tokluk.',
  },
  {
    drinkType: 'coffee_decaf',
    nametr: 'Kafeinsiz Kahve',
    nameen: 'Decaf Coffee',
    category: 'coffee',
    hydrationValue: 0.75,
    caffeinePerServing: 5,
    sugarPerServing: 0,
    defaultServingMl: 240,
    iconName: 'cafe-outline',
    color: '#8B5E3C',
    descriptiontr: 'Kafein hassasiyeti olanlar için. Aynı aroma, minimum kafein.',
  },
  {
    drinkType: 'coffee_cascara',
    nametr: 'Cascara',
    nameen: 'Cascara',
    category: 'coffee',
    hydrationValue: 0.88,
    caffeinePerServing: 25,
    sugarPerServing: 0,
    defaultServingMl: 250,
    iconName: 'leaf-outline',
    color: '#FF6B35',
    descriptiontr: 'Kahve meyvesi kabuğundan yapılan çay. Antioksidan zengini, hafif kafeinli.',
  },
  {
    drinkType: 'coffee_mushroom',
    nametr: 'Mantar Kahvesi',
    nameen: 'Mushroom Coffee',
    category: 'coffee',
    hydrationValue: 0.78,
    caffeinePerServing: 50,
    sugarPerServing: 0,
    defaultServingMl: 240,
    iconName: 'cafe',
    color: '#A2845E',
    descriptiontr: "Chaga veya Lion's Mane eklenmiş kahve. Bağışıklık ve odaklanma desteği.",
  },

  // ── Alkol ─────────────────────────────────────────────────────────────────────
  {
    drinkType: 'alcohol_beer',
    nametr: 'Bira',
    nameen: 'Beer',
    category: 'alcohol',
    hydrationValue: 0.45,
    caffeinePerServing: 0,
    sugarPerServing: 5,
    defaultServingMl: 330,
    iconName: 'beer-outline',
    color: '#FF9F0A',
    descriptiontr: 'Düşük alkol oranı, B vitamini içerir. Yüksek kalori ve dehidrasyon etkisi var.',
  },
  {
    drinkType: 'alcohol_wine_red',
    nametr: 'Kırmızı Şarap',
    nameen: 'Red Wine',
    category: 'alcohol',
    hydrationValue: 0.3,
    caffeinePerServing: 0,
    sugarPerServing: 2,
    defaultServingMl: 150,
    iconName: 'wine-outline',
    color: '#8B0000',
    descriptiontr:
      'Resveratrol içerir. Günde 1 kadeh kalp sağlığı ile ilişkilendirilmiş, fazlası zararlı.',
  },
  {
    drinkType: 'alcohol_wine_white',
    nametr: 'Beyaz Şarap',
    nameen: 'White Wine',
    category: 'alcohol',
    hydrationValue: 0.32,
    caffeinePerServing: 0,
    sugarPerServing: 4,
    defaultServingMl: 150,
    iconName: 'wine-outline',
    color: '#FFD60A',
    descriptiontr: 'Daha hafif asit profili. Kırmızı şaraba göre daha düşük antioksidan içeriği.',
  },
  {
    drinkType: 'alcohol_beer_zero',
    nametr: 'Alkolsüz Bira',
    nameen: 'Non-Alcoholic Beer',
    category: 'alcohol',
    hydrationValue: 0.85,
    caffeinePerServing: 0,
    sugarPerServing: 6,
    defaultServingMl: 330,
    iconName: 'beer-outline',
    color: '#8CD64A',
    descriptiontr: 'Alkol yok, bira aroması var. Sporcularda toparlanmayı desteklediği gösterildi.',
  },
  {
    drinkType: 'alcohol_vodka',
    nametr: 'Votka',
    nameen: 'Vodka',
    category: 'alcohol',
    hydrationValue: 0.0,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 50,
    iconName: 'warning-outline',
    color: '#5AC8FA',
    descriptiontr:
      'Saf etanol. Yoğun dehidrasyon, performans düşürücü; spor dönemlerinde kesinlikle kaçın.',
  },
  {
    drinkType: 'alcohol_whiskey',
    nametr: 'Viski',
    nameen: 'Whiskey',
    category: 'alcohol',
    hydrationValue: 0.0,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 50,
    iconName: 'wine-outline',
    color: '#A2845E',
    descriptiontr:
      'Damıtılmış tahıl içeceği. Karaciğer yükü ve uyku kalitesi bozulması önemli riskler.',
  },
  {
    drinkType: 'alcohol_gin',
    nametr: 'Cin',
    nameen: 'Gin',
    category: 'alcohol',
    hydrationValue: 0.0,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 50,
    iconName: 'warning-outline',
    color: '#5E5CE6',
    descriptiontr:
      'Ardıç aromalı damıtık. Düşük kalori ama alkol riski aynı; karıştırıcıya dikkat.',
  },
  {
    drinkType: 'alcohol_tequila',
    nametr: 'Tekila',
    nameen: 'Tequila',
    category: 'alcohol',
    hydrationValue: 0.0,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 50,
    iconName: 'warning-outline',
    color: '#FFD60A',
    descriptiontr: 'Agave bitkisinden damıtılır. Diğer içkilere göre daha az fusel yağı içerir.',
  },
  {
    drinkType: 'alcohol_rum',
    nametr: 'Rom',
    nameen: 'Rum',
    category: 'alcohol',
    hydrationValue: 0.0,
    caffeinePerServing: 0,
    sugarPerServing: 0,
    defaultServingMl: 50,
    iconName: 'wine-outline',
    color: '#8B5E3C',
    descriptiontr: 'Şeker kamışından üretilir. Tropikal kokteyllerde yaygın, yüksek kalori içerir.',
  },
  {
    drinkType: 'alcohol_champagne',
    nametr: 'Şampanya',
    nameen: 'Champagne',
    category: 'alcohol',
    hydrationValue: 0.28,
    caffeinePerServing: 0,
    sugarPerServing: 6,
    defaultServingMl: 150,
    iconName: 'wine-outline',
    color: '#FFD60A',
    descriptiontr: 'Gazlı beyaz şarap. Gaz kabarcıkları alkolün kana karışımını hızlandırır.',
  },
  {
    drinkType: 'alcohol_cocktail',
    nametr: 'Kokteyl',
    nameen: 'Cocktail',
    category: 'alcohol',
    hydrationValue: 0.2,
    caffeinePerServing: 0,
    sugarPerServing: 18,
    defaultServingMl: 200,
    iconName: 'wine-outline',
    color: '#BF5AF2',
    descriptiontr:
      'Alkol + şeker + meyve suyu karışımı. Kalori bombası; şeker ve alkol çifte risk.',
  },
  {
    drinkType: 'alcohol_sake',
    nametr: 'Sake',
    nameen: 'Sake',
    category: 'alcohol',
    hydrationValue: 0.25,
    caffeinePerServing: 0,
    sugarPerServing: 3,
    defaultServingMl: 180,
    iconName: 'wine-outline',
    color: '#F9F9FB',
    descriptiontr: 'Japon pirinç şarabı. Amino asit içerir; kültürel içecek, ılımlı tüketimde.',
  },
  {
    drinkType: 'alcohol_cider',
    nametr: 'Elmalı Şarap (Cider)',
    nameen: 'Cider',
    category: 'alcohol',
    hydrationValue: 0.4,
    caffeinePerServing: 0,
    sugarPerServing: 12,
    defaultServingMl: 330,
    iconName: 'nutrition-outline',
    color: '#34C759',
    descriptiontr: 'Fermente elma suyu. Biraya alternatif, glütensiz ama yüksek şeker içerebilir.',
  },
  {
    drinkType: 'alcohol_kefir_milk',
    nametr: 'Kefir Şarabı',
    nameen: 'Milk Kefir Wine',
    category: 'alcohol',
    hydrationValue: 0.5,
    caffeinePerServing: 0,
    sugarPerServing: 5,
    defaultServingMl: 150,
    iconName: 'shield-outline',
    color: '#F9F9FB',
    descriptiontr: 'Düşük alkollü fermente süt içeceği. Probiyotik içerir, Orta Asya geleneği.',
  },
]

export async function POST() {
  let created = 0

  for (const item of CATALOG) {
    await db.drinkCatalog.upsert({
      where: { drinkType: item.drinkType },
      create: item,
      update: {
        nametr: item.nametr,
        nameen: item.nameen,
        category: item.category,
        hydrationValue: item.hydrationValue,
        caffeinePerServing: item.caffeinePerServing,
        sugarPerServing: item.sugarPerServing,
        defaultServingMl: item.defaultServingMl,
        iconName: item.iconName,
        color: item.color,
        descriptiontr: item.descriptiontr,
      },
    })
    created++
  }

  return NextResponse.json({ created, total: CATALOG.length })
}
