import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

const SUPPLEMENTS = [
  // ─── PROTEİN ──────────────────────────────────────────────────────────────
  {
    name: 'Whey Protein Concentrate',
    category: 'Protein',
    type: 'protein',
    doseInfo: '25-30g/gün',
    benefit: 'Kas gelişimi & toparlanma',
  },
  {
    name: 'Whey Protein Isolate',
    category: 'Protein',
    type: 'protein',
    doseInfo: '25-30g/gün',
    benefit: 'Hızlı emilen saf protein, yağ & laktoz düşük',
  },
  {
    name: 'Whey Protein Hydrolysate',
    category: 'Protein',
    type: 'protein',
    doseInfo: '25-30g/gün',
    benefit: 'En hızlı emen whey, antrenman sonrası ideal',
  },
  {
    name: 'Casein Protein',
    category: 'Protein',
    type: 'protein',
    doseInfo: '30-40g/gece',
    benefit: 'Yavaş salınımlı protein, gece kullanımı için',
  },
  {
    name: 'Plant Protein (Bezelye)',
    category: 'Protein',
    type: 'protein',
    doseInfo: '25-30g/gün',
    benefit: 'Vegan protein kaynağı, kas gelişimi',
  },
  {
    name: 'Plant Protein (Pirinç+Bezelye)',
    category: 'Protein',
    type: 'protein',
    doseInfo: '25-30g/gün',
    benefit: 'Tam aminoasit profili, vegan',
  },
  {
    name: 'Soya Protein İzolatı',
    category: 'Protein',
    type: 'protein',
    doseInfo: '25-30g/gün',
    benefit: 'Bitkisel tam protein',
  },
  {
    name: 'Egg White Protein',
    category: 'Protein',
    type: 'protein',
    doseInfo: '25-30g/gün',
    benefit: 'Yüksek biyoyararlanımlı hayvansal protein',
  },
  {
    name: 'Collagen Peptides',
    category: 'Protein',
    type: 'protein',
    doseInfo: '10-20g/gün',
    benefit: 'Eklem, cilt & bağ doku sağlığı',
  },
  {
    name: 'BCAA (Dallı Zincirli Aminoasitler)',
    category: 'Protein',
    type: 'protein',
    doseInfo: '5-10g/antrenman',
    benefit: 'Kas yıkımını önler, toparlanmayı hızlandırır',
  },
  {
    name: 'EAA (Esansiyel Aminoasitler)',
    category: 'Protein',
    type: 'protein',
    doseInfo: '10-15g/gün',
    benefit: 'Protein sentezi & kas koruması',
  },
  {
    name: 'Glutamine',
    category: 'Protein',
    type: 'protein',
    doseInfo: '5-10g/gün',
    benefit: 'Bağışıklık & bağırsak sağlığı, kas toparlanması',
  },
  {
    name: 'Beta-Alanine',
    category: 'Protein',
    type: 'protein',
    doseInfo: '3.2-6.4g/gün',
    benefit: 'Kas dayanıklılığı, karnosin sentezi',
  },

  // ─── KREATİN & PERFORMANS ─────────────────────────────────────────────────
  {
    name: 'Creatine Monohydrate',
    category: 'Performans',
    type: 'kreatin',
    doseInfo: '3-5g/gün',
    benefit: 'Güç & patlayıcı performans artışı',
  },
  {
    name: 'Creatine HCL',
    category: 'Performans',
    type: 'kreatin',
    doseInfo: '1-2g/gün',
    benefit: 'Daha iyi çözünürlük, düşük doz ile etkili',
  },
  {
    name: 'Creatine Ethyl Ester',
    category: 'Performans',
    type: 'kreatin',
    doseInfo: '2-3g/gün',
    benefit: 'Hızlı emilen kreatin formu',
  },
  {
    name: 'Pre-Workout (Kafeinli)',
    category: 'Performans',
    type: 'genel',
    doseInfo: '1 porsiyon/antrenman öncesi',
    benefit: 'Enerji, odaklanma & pompa',
  },
  {
    name: 'Pre-Workout (Kafeinsiz)',
    category: 'Performans',
    type: 'genel',
    doseInfo: '1 porsiyon/antrenman öncesi',
    benefit: 'Stimülantsız pompa & dayanıklılık',
  },
  {
    name: 'Citrulline Malate',
    category: 'Performans',
    type: 'genel',
    doseInfo: '6-8g/gün',
    benefit: 'Kan akışı & kas pompası',
  },
  {
    name: 'L-Arginine',
    category: 'Performans',
    type: 'genel',
    doseInfo: '3-6g/gün',
    benefit: 'Nitrik oksit üretimi, pompa',
  },
  {
    name: 'L-Carnitine',
    category: 'Performans',
    type: 'genel',
    doseInfo: '1-3g/gün',
    benefit: 'Yağ yakımı & enerji üretimi',
  },
  {
    name: 'L-Carnitine L-Tartrate',
    category: 'Performans',
    type: 'genel',
    doseInfo: '1-2g/gün',
    benefit: 'Toparlanma & yağ metabolizması',
  },
  {
    name: 'Caffeine',
    category: 'Performans',
    type: 'genel',
    doseInfo: '100-200mg/gün',
    benefit: 'Enerji, odaklanma & performans',
  },
  {
    name: 'Nitrates (Pancar Özü)',
    category: 'Performans',
    type: 'genel',
    doseInfo: '300-600mg nitrat/gün',
    benefit: 'Dayanıklılık & oksijen verimliliği',
  },
  {
    name: 'HMB (Beta-Hydroxy Beta-Methylbutyrate)',
    category: 'Performans',
    type: 'genel',
    doseInfo: '3g/gün',
    benefit: 'Kas yıkımını önler, güç artışı',
  },

  // ─── VİTAMİN ──────────────────────────────────────────────────────────────
  {
    name: 'Vitamin A (Retinol)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '700-900mcg/gün',
    benefit: 'Görme, bağışıklık & cilt sağlığı',
  },
  {
    name: 'Vitamin B1 (Thiamine)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '1.1-1.2mg/gün',
    benefit: 'Enerji metabolizması & sinir sistemi',
  },
  {
    name: 'Vitamin B2 (Riboflavin)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '1.1-1.3mg/gün',
    benefit: 'Enerji üretimi & hücre büyümesi',
  },
  {
    name: 'Vitamin B3 (Niacin)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '14-16mg/gün',
    benefit: 'Enerji metabolizması & kolesterol',
  },
  {
    name: 'Vitamin B5 (Pantothenic Acid)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '5mg/gün',
    benefit: 'Hormon sentezi & enerji metabolizması',
  },
  {
    name: 'Vitamin B6 (Pyridoxine)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '1.3-1.7mg/gün',
    benefit: 'Protein metabolizması & sinir sistemi',
  },
  {
    name: 'Vitamin B7 (Biotin)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '30mcg/gün',
    benefit: 'Saç, tırnak & cilt sağlığı',
  },
  {
    name: 'Vitamin B9 (Folate)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '400mcg/gün',
    benefit: 'DNA sentezi & hücre bölünmesi',
  },
  {
    name: 'Vitamin B12 (Cobalamin)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '2.4mcg/gün (500-1000mcg supp)',
    benefit: 'Enerji, sinir sistemi & kan hücreleri',
  },
  {
    name: 'Vitamin C (Ascorbic Acid)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '500-1000mg/gün',
    benefit: 'Bağışıklık, antioksidan & kolajen sentezi',
  },
  {
    name: 'Vitamin D3 (Cholecalciferol)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '1000-4000 IU/gün',
    benefit: 'Kemik sağlığı, bağışıklık & testosteron',
  },
  {
    name: 'Vitamin D2 (Ergocalciferol)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '1000-2000 IU/gün',
    benefit: 'Vegan D vitamini kaynağı',
  },
  {
    name: 'Vitamin E (Tocopherol)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '15mg/gün',
    benefit: 'Antioksidan & hücre koruması',
  },
  {
    name: 'Vitamin K1 (Phylloquinone)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '90-120mcg/gün',
    benefit: 'Kan pıhtılaşması & kemik sağlığı',
  },
  {
    name: 'Vitamin K2 (MK-7)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '90-200mcg/gün',
    benefit: 'Kemik & damar sağlığı, D3 ile sinerjik',
  },
  {
    name: 'Multivitamin',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '1 tablet/gün',
    benefit: 'Tüm temel vitamin & minerallerin karşılanması',
  },
  {
    name: 'B-Complex',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '1 tablet/gün',
    benefit: 'Tüm B vitaminleri, enerji & sinir sistemi',
  },
  {
    name: 'Prenatal Vitamin',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '1 tablet/gün',
    benefit: 'Hamilelik döneminde temel besin desteği',
  },

  // ─── MİNERAL ──────────────────────────────────────────────────────────────
  {
    name: 'Magnesium Glycinate',
    category: 'Mineral',
    type: 'magnezyum',
    doseInfo: '200-400mg/gün',
    benefit: 'Uyku kalitesi, kas rahatlaması & stres',
  },
  {
    name: 'Magnesium Citrate',
    category: 'Mineral',
    type: 'magnezyum',
    doseInfo: '200-400mg/gün',
    benefit: 'Yüksek emilim, sindirim & kas fonksiyonu',
  },
  {
    name: 'Magnesium Malate',
    category: 'Mineral',
    type: 'magnezyum',
    doseInfo: '200-400mg/gün',
    benefit: 'Enerji üretimi & kas ağrısı',
  },
  {
    name: 'Magnesium L-Threonate',
    category: 'Mineral',
    type: 'magnezyum',
    doseInfo: '144mg/gün',
    benefit: 'Beyin sağlığı & bilişsel fonksiyon',
  },
  {
    name: 'Zinc Picolinate',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '15-30mg/gün',
    benefit: 'Bağışıklık, testosteron & yara iyileşmesi',
  },
  {
    name: 'Zinc Bisglycinate',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '15-30mg/gün',
    benefit: 'Yüksek emilimli çinko formu',
  },
  {
    name: 'Iron (Ferrous Bisglycinate)',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '18-27mg/gün',
    benefit: 'Kansızlık önleme, oksijen taşıma',
  },
  {
    name: 'Calcium Carbonate',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '1000-1200mg/gün',
    benefit: 'Kemik & diş sağlığı',
  },
  {
    name: 'Calcium Citrate',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '500-1000mg/gün',
    benefit: 'Yüksek emilimli kalsiyum, aç karna alınabilir',
  },
  {
    name: 'Potassium',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '99-3500mg/gün',
    benefit: 'Kalp sağlığı, kas kontraksiyonu & tansiyon',
  },
  {
    name: 'Selenium',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '55-200mcg/gün',
    benefit: 'Tiroit fonksiyonu & antioksidan koruması',
  },
  {
    name: 'Iodine',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '150mcg/gün',
    benefit: 'Tiroit hormonu üretimi & metabolizma',
  },
  {
    name: 'Chromium Picolinate',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '200-400mcg/gün',
    benefit: 'Kan şekeri dengesi & insülin duyarlılığı',
  },
  {
    name: 'Copper',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '0.9mg/gün',
    benefit: 'Demir metabolizması & bağ doku sağlığı',
  },
  {
    name: 'Manganese',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '1.8-2.3mg/gün',
    benefit: 'Kemik oluşumu & antioksidan enzimler',
  },
  {
    name: 'Boron',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '3-10mg/gün',
    benefit: 'Testosteron, kemik & beyin sağlığı',
  },
  {
    name: 'Electrolyte Complex',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '1 porsiyon/gün',
    benefit: 'Hidrasyon, kas krampı önleme',
  },

  // ─── OMEGA & YAĞ ASİTLERİ ─────────────────────────────────────────────────
  {
    name: 'Omega-3 (Balık Yağı)',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '1-3g EPA+DHA/gün',
    benefit: 'Kalp, beyin & eklem sağlığı',
  },
  {
    name: 'Omega-3 (Kril Yağı)',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '500mg-1g/gün',
    benefit: 'Yüksek biyoyararlanımlı omega-3',
  },
  {
    name: 'Omega-3 (Alg Yağı)',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '250-500mg DHA/gün',
    benefit: 'Vegan omega-3, beyin sağlığı',
  },
  {
    name: 'EPA (Eicosapentaenoic Acid)',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '1-2g/gün',
    benefit: 'İltihaplanma önleme & kalp sağlığı',
  },
  {
    name: 'DHA (Docosahexaenoic Acid)',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '500mg-1g/gün',
    benefit: 'Beyin gelişimi & bilişsel fonksiyon',
  },
  {
    name: 'Omega-6 (GLA - Çuha Çiçeği)',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '500mg-1g/gün',
    benefit: 'Cilt sağlığı & hormonal denge',
  },
  {
    name: 'Omega-7 (Deniz Topalak)',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '210mg/gün',
    benefit: 'Mukoza sağlığı & metabolizma',
  },
  {
    name: 'Omega-9 (Zeytinyağı Özü)',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '1-2g/gün',
    benefit: 'Kalp sağlığı & iltihaplanma önleme',
  },
  {
    name: 'CLA (Conjugated Linoleic Acid)',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '3-6g/gün',
    benefit: 'Yağ yakımı & vücut kompozisyonu',
  },
  {
    name: 'MCT Oil',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '1-3 yemek kaşığı/gün',
    benefit: 'Hızlı enerji, keto diyet desteği',
  },

  // ─── BİTKİ ÖZLERİ & ADAPTOJENLEr ─────────────────────────────────────────
  {
    name: 'Ashwagandha (KSM-66)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300-600mg/gün',
    benefit: 'Stres azaltma, testosteron & uyku',
  },
  {
    name: 'Rhodiola Rosea',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '200-600mg/gün',
    benefit: 'Zihinsel dayanıklılık & yorgunluk azaltma',
  },
  {
    name: 'Panax Ginseng',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '200-400mg/gün',
    benefit: 'Enerji, performans & bağışıklık',
  },
  {
    name: 'Maca Root',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '1.5-3g/gün',
    benefit: 'Libido, enerji & hormonal denge',
  },
  {
    name: 'Turmeric (Curcumin)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '500-1000mg/gün',
    benefit: 'Güçlü antiinflamatuar & antioksidan',
  },
  {
    name: 'Berberine',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '500mg 2-3x/gün',
    benefit: 'Kan şekeri dengesi & metabolizma',
  },
  {
    name: "Lion's Mane Mushroom",
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '500-1000mg/gün',
    benefit: 'Beyin sağlığı & nöroprotektif',
  },
  {
    name: 'Reishi Mushroom',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '1-2g/gün',
    benefit: 'Bağışıklık & stres adaptasyonu',
  },
  {
    name: 'Cordyceps Mushroom',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '1-3g/gün',
    benefit: 'Enerji, dayanıklılık & atletik performans',
  },
  {
    name: 'Chaga Mushroom',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '1-2g/gün',
    benefit: 'Antioksidan & bağışıklık güçlendirici',
  },
  {
    name: 'Holy Basil (Tulsi)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300-600mg/gün',
    benefit: 'Stres & kortizol yönetimi',
  },
  {
    name: 'Valerian Root',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300-600mg/gece',
    benefit: 'Uyku kalitesi & anksiyete azaltma',
  },
  {
    name: 'Milk Thistle (Silymarin)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '140-420mg/gün',
    benefit: 'Karaciğer koruması & detoks',
  },
  {
    name: 'Ginkgo Biloba',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '120-240mg/gün',
    benefit: 'Beyin kan akışı & hafıza',
  },
  {
    name: 'Saw Palmetto',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '320mg/gün',
    benefit: 'Prostat sağlığı & DHT blokajı',
  },
  {
    name: 'Black Cohosh',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '20-40mg/gün',
    benefit: 'Menopoz semptomları & hormonal denge',
  },
  {
    name: 'Elderberry (Mürver)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '500-1000mg/gün',
    benefit: 'Bağışıklık güçlendirici & antiviral',
  },
  {
    name: 'Echinacea',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300-500mg/gün',
    benefit: 'Bağışıklık desteği & soğuk algınlığı',
  },
  {
    name: 'Garlic Extract',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '600-1200mg/gün',
    benefit: 'Kalp sağlığı & antimikrobiyal',
  },
  {
    name: 'Green Tea Extract (EGCG)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '250-500mg/gün',
    benefit: 'Antioksidan, metabolizma & yağ yakımı',
  },

  // ─── PROBİYOTİK & SİNDİRİM ───────────────────────────────────────────────
  {
    name: 'Probiotic Multi-Strain',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '10-50 Milyar CFU/gün',
    benefit: 'Bağırsak florası & sindirim sağlığı',
  },
  {
    name: 'Lactobacillus Acidophilus',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '1-10 Milyar CFU/gün',
    benefit: 'Laktoz sindirimi & bağırsak sağlığı',
  },
  {
    name: 'Bifidobacterium Longum',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '1-10 Milyar CFU/gün',
    benefit: 'Bağışıklık & sindirim desteği',
  },
  {
    name: 'Saccharomyces Boulardii',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '250-500mg/gün',
    benefit: 'İshal önleme & bağırsak koruması',
  },
  {
    name: 'Prebiotic (İnülin/FOS)',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '5-10g/gün',
    benefit: 'Probiyotik besler, bağırsak sağlığı',
  },
  {
    name: 'Digestive Enzymes',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '1 kapsül/yemek',
    benefit: 'Besin emilimini artırır, şişkinliği azaltır',
  },
  {
    name: 'Psyllium Husk',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '5-10g/gün',
    benefit: 'Lif kaynağı, sindirim & kolesterol',
  },
  {
    name: 'Aloe Vera',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '100-200mg/gün',
    benefit: 'Sindirim sistemi rahatlatıcı',
  },
  {
    name: 'Apple Cider Vinegar',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '15-30ml/gün',
    benefit: 'Kan şekeri & sindirim desteği',
  },

  // ─── YAĞ YAKICI & METABOLİZMA ─────────────────────────────────────────────
  {
    name: 'Yohimbine',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '2.5-20mg/gün',
    benefit: 'Yağ yakımı, özellikle inatçı bölgeler',
  },
  {
    name: 'Green Coffee Extract',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '400-800mg/gün',
    benefit: 'Metabolizma hızlandırıcı & yağ yakımı',
  },
  {
    name: 'Garcinia Cambogia (HCA)',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '500-1000mg/gün',
    benefit: 'İştah azaltma & yağ sentezi blokajı',
  },
  {
    name: 'Synephrine (Bitter Orange)',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '10-20mg/gün',
    benefit: 'Termojenik etki & metabolizma',
  },
  {
    name: 'Capsaicin (Acı Biber Özü)',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '2-6mg/gün',
    benefit: 'Termojenik, iştah azaltma',
  },
  {
    name: 'Forskolin',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '25-60mg/gün',
    benefit: 'cAMP artışı, yağ yakımı & testosteron',
  },
  {
    name: '5-HTP',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '50-300mg/gün',
    benefit: 'Serotonin öncülü, iştah kontrolü & uyku',
  },

  // ─── EKLEM & KEMİK ────────────────────────────────────────────────────────
  {
    name: 'Glucosamine Sulfate',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '1500mg/gün',
    benefit: 'Eklem kıkırdağı koruması & ağrı azaltma',
  },
  {
    name: 'Chondroitin Sulfate',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '800-1200mg/gün',
    benefit: 'Eklem esnekliği & kıkırdak koruması',
  },
  {
    name: 'MSM (Methylsulfonylmethane)',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '1.5-3g/gün',
    benefit: 'Eklem iltihabı azaltma & esneklik',
  },
  {
    name: 'Hyaluronic Acid',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '80-200mg/gün',
    benefit: 'Eklem kayganlığı & cilt nemi',
  },
  {
    name: 'Collagen Type II',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '10-40mg/gün',
    benefit: 'Eklem kıkırdağı & romatoid artrit',
  },
  {
    name: 'Boswellia (Sünbülteber)',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '300-500mg/gün',
    benefit: 'Güçlü antiinflamatuar, eklem ağrısı',
  },

  // ─── UYKU & RAHATLAMA ─────────────────────────────────────────────────────
  {
    name: 'Melatonin',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '0.5-5mg/gece',
    benefit: 'Uyku düzeni & sirkadiyen ritim',
  },
  {
    name: 'L-Theanine',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '100-200mg/gün',
    benefit: 'Sakinleştirici, kafeinin yan etkilerini azaltır',
  },
  {
    name: 'GABA',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '500-750mg/gece',
    benefit: 'Anksiyete azaltma & uyku kalitesi',
  },
  {
    name: 'Phosphatidylserine',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '100-300mg/gün',
    benefit: 'Kortizol düşürme & beyin sağlığı',
  },
  {
    name: 'Lemon Balm',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '300-600mg/gün',
    benefit: 'Anksiyete & uyku desteği',
  },

  // ─── KAN ŞEKERİ & İNSÜLİN ────────────────────────────────────────────────
  {
    name: 'Alpha Lipoic Acid (ALA)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '300-600mg/gün',
    benefit: 'Antioksidan, insülin duyarlılığı & nöropati',
  },
  {
    name: 'Cinnamon Extract',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '500-2000mg/gün',
    benefit: 'Kan şekeri kontrolü & insülin duyarlılığı',
  },
  {
    name: 'CoQ10 (Coenzyme Q10)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '100-300mg/gün',
    benefit: 'Mitokondriyal enerji & kalp sağlığı',
  },
  {
    name: 'Resveratrol',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '100-500mg/gün',
    benefit: 'Güçlü antioksidan, yaşlanma karşıtı',
  },
  {
    name: 'Quercetin',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '500-1000mg/gün',
    benefit: 'Antihistaminik, antiinflamatuar & bağışıklık',
  },
  {
    name: 'NAC (N-Acetyl Cysteine)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '600-1800mg/gün',
    benefit: 'Glutatyon öncülü, karaciğer & akciğer sağlığı',
  },
  {
    name: 'Astaxanthin',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '4-12mg/gün',
    benefit: 'En güçlü doğal antioksidanlardan biri',
  },
  {
    name: 'Lycopene',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '10-30mg/gün',
    benefit: 'Prostat sağlığı & antioksidan',
  },
  {
    name: 'Lutein & Zeaxanthin',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '10-20mg/gün',
    benefit: 'Göz sağlığı & maküla koruması',
  },

  // ─── NOOTROPİK & BEYİN ──────────────────────────────────────────────────
  {
    name: 'Alpha GPC',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300-600mg/gün',
    benefit: 'Asetilkolin öncülü, odaklanma & hafıza',
  },
  {
    name: 'CDP-Choline (Citicoline)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '250-500mg/gün',
    benefit: 'Beyin enerjisi, hafıza & nöroproteksiyon',
  },
  {
    name: 'Bacopa Monnieri',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300-600mg/gün',
    benefit: 'Hafıza güçlendirici & anksiyete azaltma',
  },
  {
    name: 'Phosphatidylcholine',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '1-3g/gün',
    benefit: 'Hücre zarı sağlığı & karaciğer koruması',
  },
  {
    name: 'Huperzine A',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '50-200mcg/gün',
    benefit: 'Asetilkolinesteraz inhibitörü, hafıza',
  },
  {
    name: 'DMAE (Dimethylaminoethanol)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '100-300mg/gün',
    benefit: 'Zihinsel netlik & ruh hali iyileştirici',
  },

  // ─── HORMON & TEST ────────────────────────────────────────────────────────
  {
    name: 'Tongkat Ali (Eurycoma Longifolia)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '200-400mg/gün',
    benefit: 'Testosteron desteği, libido & enerji',
  },
  {
    name: 'Fadogia Agrestis',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '400-600mg/gün',
    benefit: 'LH artışı & testosteron desteği',
  },
  {
    name: 'Tribulus Terrestris',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '250-750mg/gün',
    benefit: 'Libido & atletik performans desteği',
  },
  {
    name: 'DHEA',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '25-50mg/gün',
    benefit: 'Hormon öncülü, yaşlanma karşıtı',
  },
  {
    name: 'Pregnenolone',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '10-50mg/gün',
    benefit: 'Ana hormon öncülü, hafıza & enerji',
  },

  // ─── YAŞLANMA KARŞITI ─────────────────────────────────────────────────────
  {
    name: 'NMN (Nicotinamide Mononucleotide)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '250-500mg/gün',
    benefit: 'NAD+ artışı, hücresel yaşlanma karşıtı',
  },
  {
    name: 'NR (Nicotinamide Riboside)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '250-500mg/gün',
    benefit: 'NAD+ öncülü, enerji metabolizması',
  },
  {
    name: 'Fisetin',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '100-200mg/gün',
    benefit: 'Senolit, antioksidan & nöroprotektif',
  },
  {
    name: 'Spermidine',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '1-2mg/gün',
    benefit: 'Otofaji aktivasyonu, yaşlanma karşıtı',
  },
  {
    name: 'PQQ (Pyrroloquinoline Quinone)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '10-20mg/gün',
    benefit: 'Mitokondri büyümesi & nöroproteksiyon',
  },

  // ─── UYKU & STRES (EK) ───────────────────────────────────────────────────
  {
    name: 'L-Tryptophan',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '500-2000mg/gün',
    benefit: 'Serotonin & melatonin öncülü, uyku & mood',
  },
  {
    name: 'Glycine',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '3-5g/gece',
    benefit: 'Uyku kalitesi & vücut ısısı düzenlemesi',
  },
  {
    name: 'Apigenin',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '50mg/gece',
    benefit: 'Doğal anksiyolitik, uyku geçişini kolaylaştırır',
  },
  {
    name: 'Inositol (Myo-Inositol)',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '500-4000mg/gün',
    benefit: 'OKB, anksiyete & PKOS semptomları',
  },
  {
    name: 'Magnesium Oxide',
    category: 'Mineral',
    type: 'magnezyum',
    doseInfo: '250-500mg/gün',
    benefit: 'Temel magnezyum desteği, konstipasyon',
  },
  {
    name: 'Magnesium Taurate',
    category: 'Mineral',
    type: 'magnezyum',
    doseInfo: '125-500mg/gün',
    benefit: 'Kalp sağlığı & kan şekeri dengesi',
  },
  {
    name: 'SAMe (S-Adenosyl Methionine)',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '400-1600mg/gün',
    benefit: 'Ruh hali, karaciğer & eklem sağlığı',
  },

  // ─── PERFORMANS (EK) ────────────────────────────────────────────────────
  {
    name: 'Taurine',
    category: 'Performans',
    type: 'genel',
    doseInfo: '1-3g/gün',
    benefit: 'Hücre hidrasyonu, dayanıklılık & kalp sağlığı',
  },
  {
    name: 'L-Tyrosine',
    category: 'Performans',
    type: 'genel',
    doseInfo: '500-2000mg/gün',
    benefit: 'Dopamin öncülü, odaklanma & stres dayanıklılığı',
  },
  {
    name: 'Betaine Anhydrous',
    category: 'Performans',
    type: 'genel',
    doseInfo: '2.5g/gün',
    benefit: 'Güç, hacim & homosistein azaltma',
  },
  {
    name: 'Agmatine Sulfate',
    category: 'Performans',
    type: 'genel',
    doseInfo: '500-1500mg/gün',
    benefit: 'Nitrik oksit düzenlemesi & ağrı yönetimi',
  },
  {
    name: 'Peak ATP',
    category: 'Performans',
    type: 'genel',
    doseInfo: '400mg/gün',
    benefit: 'Güç çıkışı & kas aktivasyonu',
  },
  {
    name: 'Rhodiola + Ashwagandha Stack',
    category: 'Performans',
    type: 'genel',
    doseInfo: '1 porsiyon/gün',
    benefit: 'Adaptojenik performans & stres yönetimi',
  },

  // ─── YEŞİL GIDA & SÜPER GIDA ─────────────────────────────────────────────
  {
    name: 'Spirulina',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '3-10g/gün',
    benefit: 'Protein, demir & antioksidan zengini süper gıda',
  },
  {
    name: 'Chlorella',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '3-10g/gün',
    benefit: 'Detoks, ağır metal temizleme & bağışıklık',
  },
  {
    name: 'Moringa',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '2-5g/gün',
    benefit: 'Vitamin, mineral & antioksidan açısından zengin',
  },
  {
    name: 'Wheat Grass',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '3-5g/gün',
    benefit: 'Alkalize edici, klorofil & enzim kaynağı',
  },
  {
    name: 'Barley Grass',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '3-5g/gün',
    benefit: 'Antioksidan, B vitamini & enzim kaynağı',
  },
  {
    name: 'Acai Berry Extract',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '500-1000mg/gün',
    benefit: 'Yüksek ORAC antioksidan & kalp sağlığı',
  },

  // ─── KİLO YÖNETİMİ & METABOLİZMA ────────────────────────────────────────
  {
    name: 'Glucomannan (Konjak)',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '1-4g/öğün öncesi',
    benefit: 'Tokluk hissi, kan şekeri & kolesterol',
  },
  {
    name: 'White Kidney Bean Extract',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '500-1500mg/gün',
    benefit: 'Karbonhidrat emilimini bloke eder',
  },
  {
    name: 'Gymnema Sylvestre',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '200-400mg/gün',
    benefit: 'Şeker isteğini azaltır & kan şekeri dengesi',
  },
  {
    name: 'Irvingia Gabonensis',
    category: 'Yağ Yakıcı',
    type: 'genel',
    doseInfo: '150mg 2x/gün',
    benefit: 'Leptin duyarlılığı & yağ yakımı',
  },
  {
    name: 'Acetyl L-Carnitine (ALCAR)',
    category: 'Performans',
    type: 'genel',
    doseInfo: '500-2000mg/gün',
    benefit: 'Beyin enerjisi, nöroproteksiyon & yağ metabolizması',
  },

  // ─── KADINLAR & ERKEKLER ÖZEL ────────────────────────────────────────────
  {
    name: 'Evening Primrose Oil',
    category: 'Yağ Asidi',
    type: 'omega',
    doseInfo: '500-1500mg/gün',
    benefit: 'Hormonal denge, cilt & PMS semptomları',
  },
  {
    name: 'Vitex (Chasteberry)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '20-40mg/gün',
    benefit: 'PMS, hormonal denge & düzensiz adet',
  },
  {
    name: 'DIM (Diindolylmethane)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '100-200mg/gün',
    benefit: 'Östrojen metabolizması & hormonal denge',
  },
  {
    name: 'Nettle Root Extract',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300-600mg/gün',
    benefit: 'Prostat sağlığı & serbest testosteron artışı',
  },

  // ─── BAĞIŞIKLIK & VİRÜS KARŞITI ──────────────────────────────────────────
  {
    name: 'Beta-Glucan',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '250-500mg/gün',
    benefit: 'Bağışıklık modülatörü & kolesterol',
  },
  {
    name: 'Olive Leaf Extract',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '500-1000mg/gün',
    benefit: 'Antiviral, antibakteriyal & kalp sağlığı',
  },
  {
    name: 'Andrographis',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '400mg/gün',
    benefit: 'Güçlü antiviral & bağışıklık stimülan',
  },
  {
    name: 'Propolis',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300-500mg/gün',
    benefit: 'Antimikrobiyal, antiinflamatuar & bağışıklık',
  },

  // ─── KARACİĞER & DETOKS ──────────────────────────────────────────────────
  {
    name: 'TUDCA (Tauroursodeoxycholic Acid)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '250-500mg/gün',
    benefit: 'Karaciğer koruması & safra asidi desteği',
  },
  {
    name: 'Artichoke Extract',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300-600mg/gün',
    benefit: 'Karaciğer & safra kesesi sağlığı',
  },
  {
    name: 'Dandelion Root',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '500-1000mg/gün',
    benefit: 'Doğal diüretik, karaciğer & sindirim',
  },

  // ─── NÖROLOJİK & RUH HALİ ────────────────────────────────────────────────
  {
    name: 'Saffron Extract',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '28-30mg/gün',
    benefit: 'Ruh hali düzenleme, hafif depresyon & iştah',
  },
  {
    name: 'St. Johns Wort',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '300mg 3x/gün',
    benefit: 'Hafif-orta depresyon & anksiyete',
  },
  {
    name: 'Mucuna Pruriens',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '400-500mg/gün',
    benefit: 'Dopamin öncülü (L-DOPA), mood & testosteron',
  },

  // ─── EK FORM VİTAMİN/MİNERAL ─────────────────────────────────────────────
  {
    name: 'Lithium Orotate',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '5-20mg/gün',
    benefit: 'Nöroprotektor, ruh hali dengeleme',
  },
  {
    name: 'Vanadium',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '10-30mcg/gün',
    benefit: 'İnsülin duyarlılığı & kan şekeri',
  },
  {
    name: 'Silica (Silicon Dioxide)',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '10-40mg/gün',
    benefit: 'Saç, tırnak, kemik & cilt sağlığı',
  },
  {
    name: 'Strontium',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '340-680mg/gün',
    benefit: 'Kemik yoğunluğu & osteoporoz önleme',
  },
  {
    name: 'Vitamin D3 + K2 Kombinasyonu',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '2000-5000 IU D3 + 100-200mcg K2/gün',
    benefit: 'Kemik sağlığı, kalsiyum yönlendirme & bağışıklık',
  },

  // ─── EKLEM & TOPARLANMA (EK) ────────────────────────────────────────────
  {
    name: 'Cissus Quadrangularis',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '500-1000mg/gün',
    benefit: 'Eklem & tendon iyileşmesi, kırık onarımı',
  },
  {
    name: 'Bromelain',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '200-400mg/gün',
    benefit: 'Ananas enzimi, iltihaplanma & ödem azaltma',
  },
  {
    name: 'Serrapeptase',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '10-60mg/gün',
    benefit: 'Proteolitik enzim, iltihaplanma & ağrı',
  },
  {
    name: 'Undenatured Collagen (UC-II)',
    category: 'Eklem & Kemik',
    type: 'genel',
    doseInfo: '40mg/gün',
    benefit: 'Oral tolerans mekanizması ile eklem koruması',
  },

  // ─── PERFORMANS & PROTEİN (EK) ───────────────────────────────────────────
  {
    name: 'Kre-Alkalyn (Buffered Creatine)',
    category: 'Performans',
    type: 'kreatin',
    doseInfo: '1.5-3g/gün',
    benefit: 'Tamponlanmış kreatin, mide dostu & stabil',
  },
  {
    name: 'ZMA (Zinc+Magnesium+B6)',
    category: 'Performans',
    type: 'genel',
    doseInfo: '1 porsiyon/gece',
    benefit: 'Uyku kalitesi, testosteron & toparlanma',
  },
  {
    name: 'Carnosine',
    category: 'Performans',
    type: 'genel',
    doseInfo: '1-2g/gün',
    benefit: 'Kas tampon kapasitesi, antioksidan & yaşlanma karşıtı',
  },
  {
    name: 'Sodium Bicarbonate',
    category: 'Performans',
    type: 'genel',
    doseInfo: '0.2-0.3g/kg antrenman öncesi',
    benefit: 'Laktik asit tamponlama, dayanıklılık & güç',
  },
  {
    name: 'Beef Protein Isolate',
    category: 'Protein',
    type: 'protein',
    doseInfo: '25-30g/gün',
    benefit: 'Laktoz & glütensiz hayvansal protein, kas gelişimi',
  },
  {
    name: 'Hemp Protein',
    category: 'Protein',
    type: 'protein',
    doseInfo: '30g/gün',
    benefit: 'Vegan tam protein, omega-3 & lif kaynağı',
  },

  // ─── BİLİŞSEL & NÖROLOJİK (EK) ─────────────────────────────────────────
  {
    name: 'Pycnogenol (Çam Kabuğu Özü)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '50-200mg/gün',
    benefit: 'Güçlü antioksidan, kan akışı & bilişsel fonksiyon',
  },
  {
    name: 'Vinpocetine',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '10-30mg/gün',
    benefit: 'Beyin kan akışı, hafıza & nöroproteksiyon',
  },
  {
    name: 'Gotu Kola (Centella Asiatica)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '500-1000mg/gün',
    benefit: 'Beyin sağlığı, yara iyileşmesi & anksiyete',
  },
  {
    name: 'Schisandra Berry',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '500-2000mg/gün',
    benefit: 'Adaptojenik, karaciğer koruması & stres dayanıklılığı',
  },

  // ─── ANTİOKSİDAN & BİTKİ (EK) ───────────────────────────────────────────
  {
    name: 'Grape Seed Extract',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '100-300mg/gün',
    benefit: 'Güçlü OPC antioksidanı, damar & cilt sağlığı',
  },
  {
    name: 'Tart Cherry Extract',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '480mg/gün',
    benefit: 'Toparlanma, uyku kalitesi & iltihaplanma azaltma',
  },
  {
    name: 'Pomegranate Extract',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '500-1000mg/gün',
    benefit: 'Punicalagin antioksidanı, kalp & prostat sağlığı',
  },
  {
    name: 'Black Seed Oil (Nigella Sativa)',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '1-3g/gün',
    benefit: 'Bağışıklık, antiinflamatuar & metabolizma desteği',
  },
  {
    name: 'Astragalus',
    category: 'Bitki',
    type: 'probiyotik',
    doseInfo: '500-1500mg/gün',
    benefit: 'Telomer uzatma, bağışıklık & adaptojenik etki',
  },
  {
    name: 'Passion Flower (Çarkıfelek)',
    category: 'Uyku & Rahatlama',
    type: 'genel',
    doseInfo: '250-500mg/gün',
    benefit: 'Anksiyete azaltma, uyku kalitesi & GABA desteği',
  },

  // ─── VİTAMİN/MİNERAL AKTİF FORMLAR ─────────────────────────────────────
  {
    name: 'Methylcobalamin (B12 Aktif Form)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '500-1000mcg/gün',
    benefit: "B12'nin biyoaktif formu, sinir sistemi & metilasyon",
  },
  {
    name: 'Methylfolate (5-MTHF)',
    category: 'Vitamin',
    type: 'vitamin',
    doseInfo: '400-800mcg/gün',
    benefit: "Folat'ın aktif formu, MTHFR mutasyonu & metilasyon",
  },
  {
    name: 'Ubiquinol (CoQ10 Aktif Form)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '100-200mg/gün',
    benefit: "CoQ10'un indirgenmiş aktif formu, üstün emilim",
  },
  {
    name: 'Tocotrienols (E Vitamini)',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '100-300mg/gün',
    benefit: 'Tokoferolden 50x güçlü E vitamini formu, nöroprotektif',
  },
  {
    name: 'Pterostilbene',
    category: 'Antioksidan',
    type: 'genel',
    doseInfo: '50-250mg/gün',
    benefit: 'Resveratrolün güçlü analoğu, daha iyi biyoyararlanım',
  },

  // ─── BAĞIRSAK & İMMÜN (EK) ──────────────────────────────────────────────
  {
    name: 'Colostrum (Ağız Sütü)',
    category: 'Probiyotik',
    type: 'probiyotik',
    doseInfo: '500-2000mg/gün',
    benefit: 'Bağırsak bütünlüğü, bağışıklık & büyüme faktörleri',
  },
  {
    name: 'Zinc Carnosine',
    category: 'Mineral',
    type: 'genel',
    doseInfo: '75-150mg/gün',
    benefit: 'Mide mukozası koruması & bağırsak sağlığı',
  },
]

async function main() {
  console.log(`Seeding ${SUPPLEMENTS.length} supplements...`)

  // Önce mevcut global kayıtları temizle
  await db.supplementCatalog.deleteMany({ where: { country: 'global' } })
  console.log('Cleared existing global catalog')

  // Batch insert
  const result = await db.supplementCatalog.createMany({
    data: SUPPLEMENTS.map((s) => ({
      name: s.name,
      brand: null,
      category: s.category,
      type: s.type,
      country: 'global',
      doseInfo: s.doseInfo,
      benefit: s.benefit,
    })),
    skipDuplicates: true,
  })

  console.log(`✓ Seeded ${result.count} supplements`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => db.$disconnect())
