// Analytics and AI Memory types for Phase 6

// User Embedding - 768-dimensional vector representation of user preferences and patterns
export interface UserEmbedding {
  userId: string
  embedding: number[] // 768 dimensions
  mealPreferences: {
    cuisines: string[]
    ingredients: string[]
    avgMacros: { protein: number; carbs: number; fat: number }
  }
  workoutPreferences: {
    favoriteExercises: string[]
    avgIntensity: number // 1-10
    frequency: string // 'daily', 'weekly', etc
  }
  healthPatterns: {
    avgSleep: number
    avgSteps: number
    heartRateRange: [number, number]
  }
  socialPatterns: {
    friendCount: number
    challengeParticipation: number
    badgeEarningRate: number
  }
  lastUpdated: string // ISO
}

// Recommendation - personalized suggestions based on user embeddings
export interface Recommendation {
  id: string
  userId: string
  type: 'meal' | 'workout' | 'health' | 'friend' | 'challenge' | 'coaching'
  title: string
  description: string
  confidence: number // 0-100
  reasoning: string
  actionUrl?: string
  createdAt: string // ISO
  expiresAt: string // ISO
}

// Coaching Insight - AI-generated insights from Claude
export interface CoachingInsight {
  id: string
  userId: string
  domain: 'performance' | 'nutrition' | 'recovery' | 'behavioral'
  title: string
  insight: string // Generated by Claude
  data: Record<string, any>
  actionable: boolean
  suggestedAction?: string
  createdAt: string // ISO
}

// Analytics Summary - comprehensive user stats
export interface AnalyticsSummary {
  userId: string
  period: 'daily' | 'weekly' | 'monthly'
  workoutStats: {
    totalWorkouts: number
    totalDuration: number // minutes
    avgIntensity: number // 1-10
    favoriteExercise: string
    progressTrend: 'up' | 'flat' | 'down'
  }
  nutritionStats: {
    avgCalories: number
    avgProtein: number
    mealsLogged: number
    consistencyScore: number // 0-100
    favoriteMeals: string[]
  }
  healthStats: {
    avgSleep: number
    avgSteps: number
    avgHeartRate: number
    sleepQuality: number // 1-10
  }
  socialStats: {
    friends: number
    challengesCompleted: number
    badgesEarned: number
    totalPoints: number
  }
  goals: {
    calorieGoal: number
    calorieActual: number
    proteinGoal: number
    proteinActual: number
    workoutGoal: number
    workoutActual: number
    stepGoal: number
    stepActual: number
  }
}
