import { NextResponse } from 'next/server'
import { db } from '@/lib/db/client'

const CATALOG = [
  // Cardio
  {
    activityType: 'running',
    nametr: 'Koşu',
    nameen: 'Running',
    category: 'cardio',
    metValue: 9.8,
    hasDistance: true,
    iconName: 'walk',
    color: '#FF6B35',
    descriptiontr: 'Adım adım ilerliyorsun — hem beden hem zihin için harika bir temizlik.',
  },
  {
    activityType: 'walking',
    nametr: 'Yürüyüş',
    nameen: 'Walking',
    category: 'cardio',
    metValue: 3.5,
    hasDistance: true,
    iconName: 'footsteps',
    color: '#FF9F0A',
    descriptiontr: 'Düzenli yapıldığında mucizeler yaratan, sade ama güçlü bir alışkanlık.',
  },
  {
    activityType: 'cycling',
    nametr: 'Bisiklet',
    nameen: 'Cycling',
    category: 'cardio',
    metValue: 7.5,
    hasDistance: true,
    iconName: 'bicycle',
    color: '#30D158',
    descriptiontr: 'Hem ulaşım hem egzersiz. Pedal çevirdikçe kaloriler de gidiyor.',
  },
  {
    activityType: 'jump_rope',
    nametr: 'İp Atlama',
    nameen: 'Jump Rope',
    category: 'cardio',
    metValue: 11.0,
    hasDistance: false,
    iconName: 'repeat',
    color: '#FF3B30',
    descriptiontr: 'Küçük alan, büyük etki. Kardiyonun en yoğun ve eğlenceli hali.',
  },
  {
    activityType: 'rowing',
    nametr: 'Kürek',
    nameen: 'Rowing',
    category: 'cardio',
    metValue: 7.0,
    hasDistance: true,
    iconName: 'boat',
    color: '#0A84FF',
    descriptiontr: 'Tüm vücudu çalıştırır, düşük eklem baskısıyla yüksek verim sağlar.',
  },
  {
    activityType: 'elliptical',
    nametr: 'Eliptik',
    nameen: 'Elliptical',
    category: 'cardio',
    metValue: 5.0,
    hasDistance: false,
    iconName: 'sync',
    color: '#5E5CE6',
    descriptiontr: 'Eklemlere nazik, kalbe dürüst. Saatlerce sürdürebilirsin.',
  },
  {
    activityType: 'stepper',
    nametr: 'Stepper',
    nameen: 'Stepper',
    category: 'cardio',
    metValue: 5.5,
    hasDistance: false,
    iconName: 'trending-up',
    color: '#FF6B35',
    descriptiontr: 'Her adımda bacakları ve kalp atışını birlikte yükselt.',
  },
  {
    activityType: 'orbitrek',
    nametr: 'Orbitrek',
    nameen: 'Cross Trainer',
    category: 'cardio',
    metValue: 4.8,
    hasDistance: false,
    iconName: 'git-merge',
    color: '#30D158',
    descriptiontr: 'Üst ve alt vücudu dengeli çalıştıran, eklem dostu bir kardio aleti.',
  },
  // Su Sporları
  {
    activityType: 'swimming',
    nametr: 'Yüzme',
    nameen: 'Swimming',
    category: 'water',
    metValue: 8.0,
    hasDistance: true,
    iconName: 'water',
    color: '#0A84FF',
    descriptiontr: 'Suyun direnci tüm kasları çalıştırır. Hem serinletir hem güçlendirir.',
  },
  {
    activityType: 'water_polo',
    nametr: 'Su Topu',
    nameen: 'Water Polo',
    category: 'water',
    metValue: 10.0,
    hasDistance: false,
    iconName: 'beaker',
    color: '#5AC8FA',
    descriptiontr: 'Takım ruhu ve yoğun kardio bir arada. Suda tam gaz.',
  },
  // Toparlanma
  {
    activityType: 'sauna',
    nametr: 'Sauna',
    nameen: 'Sauna',
    category: 'recovery',
    metValue: 1.5,
    hasDistance: false,
    iconName: 'thermometer',
    color: '#FF9F0A',
    descriptiontr: 'Kasları gevşetir, zihni boşaltır. En iyi antrenman sonrası ritüel.',
  },
  {
    activityType: 'cold_pool',
    nametr: 'Şok Havuzu',
    nameen: 'Cold Pool',
    category: 'recovery',
    metValue: 2.0,
    hasDistance: false,
    iconName: 'snow',
    color: '#5AC8FA',
    descriptiontr: 'Birkaç saniye cesaret, saatler süren enerji. Vücudu sıfırlar.',
  },
  {
    activityType: 'massage',
    nametr: 'Masaj',
    nameen: 'Massage',
    category: 'recovery',
    metValue: 1.2,
    hasDistance: false,
    iconName: 'hand-left',
    color: '#BF5AF2',
    descriptiontr: 'Kas gerilimini çözer, iyileşmeyi hızlandırır. Hak ettin.',
  },
  {
    activityType: 'stretching',
    nametr: 'Esneme',
    nameen: 'Stretching',
    category: 'recovery',
    metValue: 2.5,
    hasDistance: false,
    iconName: 'resize',
    color: '#34C759',
    descriptiontr: 'Günün sonunda vücuduna teşekkür etmenin en iyi yolu.',
  },
  // Spor
  {
    activityType: 'tennis',
    nametr: 'Tenis',
    nameen: 'Tennis',
    category: 'sport',
    metValue: 7.3,
    hasDistance: false,
    iconName: 'tennisball',
    color: '#FFD60A',
    descriptiontr: 'Refleksleri keskinleştirir, raketi tutan elden kalbe kadar çalışır.',
  },
  {
    activityType: 'padel',
    nametr: 'Padel',
    nameen: 'Padel',
    category: 'sport',
    metValue: 6.5,
    hasDistance: false,
    iconName: 'tennisball-outline',
    color: '#FF9F0A',
    descriptiontr: 'Tenisin daha sosyal, daha eğlenceli kuzeni. Çabuk bağımlılık yapar.',
  },
  {
    activityType: 'football',
    nametr: 'Futbol',
    nameen: 'Football',
    category: 'sport',
    metValue: 8.0,
    hasDistance: false,
    iconName: 'football',
    color: '#30D158',
    descriptiontr: 'Takım oyunu, yüksek tempo. Sahaya çıkınca kaloriler saymayı unut.',
  },
  {
    activityType: 'basketball',
    nametr: 'Basketbol',
    nameen: 'Basketball',
    category: 'sport',
    metValue: 8.0,
    hasDistance: false,
    iconName: 'basketball',
    color: '#FF6B35',
    descriptiontr: 'Sıçrama, sprint, refleks — hepsi bir arada. Kortla sevişmek gibi.',
  },
  {
    activityType: 'volleyball',
    nametr: 'Voleybol',
    nameen: 'Volleyball',
    category: 'sport',
    metValue: 6.0,
    hasDistance: false,
    iconName: 'grid',
    color: '#0A84FF',
    descriptiontr: 'Koordinasyon ve takım çalışmasının buluştuğu, keyifli bir spor.',
  },
  {
    activityType: 'golf',
    nametr: 'Golf',
    nameen: 'Golf',
    category: 'sport',
    metValue: 4.8,
    hasDistance: false,
    iconName: 'golf',
    color: '#34C759',
    descriptiontr: 'Sakin görünür, ama konsantrasyon ve sabır ister. Her vuruş önemli.',
  },
  {
    activityType: 'boxing',
    nametr: 'Boks',
    nameen: 'Boxing',
    category: 'sport',
    metValue: 9.0,
    hasDistance: false,
    iconName: 'hand-right',
    color: '#FF3B30',
    descriptiontr: 'Stres atmak ve güçlenmek için eşsiz. Hem zihin hem beden kampa girer.',
  },
  {
    activityType: 'hiking',
    nametr: 'Doğa Yürüyüşü',
    nameen: 'Hiking',
    category: 'sport',
    metValue: 6.0,
    hasDistance: true,
    iconName: 'trail-sign',
    color: '#34C759',
    descriptiontr: 'Doğayla buluşmanın en saf hali. Her adımda hem yürür hem nefes alırsın.',
  },
  // Zihin & Beden
  {
    activityType: 'yoga',
    nametr: 'Yoga',
    nameen: 'Yoga',
    category: 'mind_body',
    metValue: 3.0,
    hasDistance: false,
    iconName: 'body',
    color: '#BF5AF2',
    descriptiontr: 'Nefes, denge ve huzur. Sadece vücudu değil, zihni de esnetir.',
  },
  {
    activityType: 'pilates',
    nametr: 'Pilates',
    nameen: 'Pilates',
    category: 'mind_body',
    metValue: 3.5,
    hasDistance: false,
    iconName: 'accessibility',
    color: '#5E5CE6',
    descriptiontr: 'Core kaslarını derinlemesine çalıştırır. Postür ve denge için birebir.',
  },
  {
    activityType: 'meditation',
    nametr: 'Meditasyon',
    nameen: 'Meditation',
    category: 'mind_body',
    metValue: 1.0,
    hasDistance: false,
    iconName: 'leaf',
    color: '#30D158',
    descriptiontr: 'Beynin de dinlenmeye ihtiyacı var. Günde birkaç dakika, fark yaratır.',
  },
  {
    activityType: 'dance',
    nametr: 'Dans',
    nameen: 'Dance',
    category: 'mind_body',
    metValue: 5.5,
    hasDistance: false,
    iconName: 'musical-note',
    color: '#FF2D55',
    descriptiontr: 'Müziğin ritmiyle hareket etmek — farkında bile olmadan egzersiz yaparsın.',
  },
  {
    activityType: 'other',
    nametr: 'Diğer',
    nameen: 'Other',
    category: 'other',
    metValue: 4.0,
    hasDistance: false,
    iconName: 'ellipsis-horizontal',
    color: '#8E8E93',
    descriptiontr: 'Her aktivite sayılır. Hareket ettikten sonra kaydet, ilerlemeye devam et.',
  },
]

export async function POST() {
  let created = 0
  let skipped = 0

  for (const item of CATALOG) {
    const result = await db.activityCatalog.upsert({
      where: { activityType: item.activityType },
      create: item,
      update: {
        nametr: item.nametr,
        nameen: item.nameen,
        metValue: item.metValue,
        iconName: item.iconName,
        color: item.color,
        descriptiontr: item.descriptiontr,
      },
    })
    if (result.createdAt.getTime() === result.createdAt.getTime()) created++
  }
  skipped = 0

  return NextResponse.json({ created, skipped, total: CATALOG.length })
}
