import { NextResponse } from 'next/server'
import { db } from '@/lib/db/client'

const SUBTYPES = [
  // ── KOŞU ──────────────────────────────────────────────────────────────────
  {
    activityType: 'running',
    key: 'running_road',
    nametr: 'Yol Koşusu',
    nameen: 'Road Running',
    metValue: 9.8,
    iconName: 'running_road',
    intensity: 'high',
  },
  {
    activityType: 'running',
    key: 'running_trail',
    nametr: 'Parkur / Trail',
    nameen: 'Trail Running',
    metValue: 11.0,
    iconName: 'running_trail',
    intensity: 'high',
  },
  {
    activityType: 'running',
    key: 'running_treadmill',
    nametr: 'Koşu Bandı',
    nameen: 'Treadmill',
    metValue: 9.0,
    iconName: 'running_treadmill',
    intensity: 'high',
  },
  {
    activityType: 'running',
    key: 'running_interval',
    nametr: 'Interval',
    nameen: 'Interval',
    metValue: 12.5,
    iconName: 'running_interval',
    intensity: 'high',
  },
  {
    activityType: 'running',
    key: 'running_marathon',
    nametr: 'Maraton Temposu',
    nameen: 'Marathon Pace',
    metValue: 10.5,
    iconName: 'running_marathon',
    intensity: 'high',
  },
  // ── YÜRÜYÜŞ ───────────────────────────────────────────────────────────────
  {
    activityType: 'walking',
    key: 'walking_urban',
    nametr: 'Şehir Yürüyüşü',
    nameen: 'Urban Walk',
    metValue: 3.5,
    iconName: 'walking_urban',
    intensity: 'low',
  },
  {
    activityType: 'walking',
    key: 'walking_nature',
    nametr: 'Doğa Yürüyüşü',
    nameen: 'Nature Walk',
    metValue: 4.0,
    iconName: 'walking_nature',
    intensity: 'low',
  },
  {
    activityType: 'walking',
    key: 'walking_nordic',
    nametr: 'Nordic Yürüyüş',
    nameen: 'Nordic Walking',
    metValue: 4.8,
    iconName: 'walking_nordic',
    intensity: 'medium',
  },
  {
    activityType: 'walking',
    key: 'walking_brisk',
    nametr: 'Tempolu Yürüyüş',
    nameen: 'Brisk Walking',
    metValue: 4.3,
    iconName: 'walking_brisk',
    intensity: 'medium',
  },
  // ── BİSİKLET ──────────────────────────────────────────────────────────────
  {
    activityType: 'cycling',
    key: 'cycling_road',
    nametr: 'Yol Bisikleti',
    nameen: 'Road Cycling',
    metValue: 8.0,
    iconName: 'cycling_road',
    intensity: 'high',
  },
  {
    activityType: 'cycling',
    key: 'cycling_mountain',
    nametr: 'Dağ Bisikleti',
    nameen: 'Mountain Bike',
    metValue: 8.5,
    iconName: 'cycling_mountain',
    intensity: 'high',
  },
  {
    activityType: 'cycling',
    key: 'cycling_stationary',
    nametr: 'Sabit Bisiklet',
    nameen: 'Stationary Bike',
    metValue: 6.8,
    iconName: 'cycling_stationary',
    intensity: 'medium',
  },
  {
    activityType: 'cycling',
    key: 'cycling_city',
    nametr: 'Şehir Bisikleti',
    nameen: 'City Cycling',
    metValue: 5.5,
    iconName: 'cycling_city',
    intensity: 'low',
  },
  // ── FUTBOL ────────────────────────────────────────────────────────────────
  {
    activityType: 'football',
    key: 'football_halisaha',
    nametr: 'Halısaha',
    nameen: 'Futsal',
    metValue: 9.0,
    iconName: 'football_halisaha',
    intensity: 'high',
  },
  {
    activityType: 'football',
    key: 'football_match',
    nametr: 'Resmi Maç',
    nameen: 'Match',
    metValue: 10.0,
    iconName: 'football_match',
    intensity: 'high',
  },
  {
    activityType: 'football',
    key: 'football_training',
    nametr: 'Antrenman',
    nameen: 'Training',
    metValue: 7.0,
    iconName: 'football_training',
    intensity: 'medium',
  },
  {
    activityType: 'football',
    key: 'football_beach',
    nametr: 'Plaj Futbolu',
    nameen: 'Beach Football',
    metValue: 8.0,
    iconName: 'football_beach',
    intensity: 'high',
  },
  // ── YÜZME ─────────────────────────────────────────────────────────────────
  {
    activityType: 'swimming',
    key: 'swimming_pool',
    nametr: 'Havuz',
    nameen: 'Pool',
    metValue: 8.0,
    iconName: 'swimming_pool',
    intensity: 'medium',
  },
  {
    activityType: 'swimming',
    key: 'swimming_sea',
    nametr: 'Deniz / Açık Su',
    nameen: 'Open Water',
    metValue: 9.0,
    iconName: 'swimming_sea',
    intensity: 'high',
  },
  {
    activityType: 'swimming',
    key: 'swimming_laps',
    nametr: 'Tempolu Yüzme',
    nameen: 'Lap Swimming',
    metValue: 10.0,
    iconName: 'swimming_laps',
    intensity: 'high',
  },
  {
    activityType: 'swimming',
    key: 'swimming_therapy',
    nametr: 'Su Terapisi',
    nameen: 'Aqua Therapy',
    metValue: 4.0,
    iconName: 'swimming_therapy',
    intensity: 'low',
  },
  // ── TENİS ─────────────────────────────────────────────────────────────────
  {
    activityType: 'tennis',
    key: 'tennis_match',
    nametr: 'Maç',
    nameen: 'Match',
    metValue: 8.0,
    iconName: 'tennis_match',
    intensity: 'high',
  },
  {
    activityType: 'tennis',
    key: 'tennis_training',
    nametr: 'Antrenman',
    nameen: 'Training',
    metValue: 6.0,
    iconName: 'tennis_training',
    intensity: 'medium',
  },
  {
    activityType: 'tennis',
    key: 'tennis_doubles',
    nametr: 'Çiftler',
    nameen: 'Doubles',
    metValue: 7.0,
    iconName: 'tennis_doubles',
    intensity: 'medium',
  },
  // ── BASKETBOL ─────────────────────────────────────────────────────────────
  {
    activityType: 'basketball',
    key: 'basketball_match',
    nametr: 'Maç',
    nameen: 'Match',
    metValue: 9.0,
    iconName: 'basketball_match',
    intensity: 'high',
  },
  {
    activityType: 'basketball',
    key: 'basketball_training',
    nametr: 'Antrenman',
    nameen: 'Training',
    metValue: 7.0,
    iconName: 'basketball_training',
    intensity: 'medium',
  },
  {
    activityType: 'basketball',
    key: 'basketball_street',
    nametr: 'Sokak Basketbolu',
    nameen: 'Street Ball',
    metValue: 8.0,
    iconName: 'basketball_street',
    intensity: 'high',
  },
  // ── VOLEYBOL ──────────────────────────────────────────────────────────────
  {
    activityType: 'volleyball',
    key: 'volleyball_match',
    nametr: 'Maç',
    nameen: 'Match',
    metValue: 7.0,
    iconName: 'volleyball_match',
    intensity: 'high',
  },
  {
    activityType: 'volleyball',
    key: 'volleyball_training',
    nametr: 'Antrenman',
    nameen: 'Training',
    metValue: 5.0,
    iconName: 'volleyball_training',
    intensity: 'medium',
  },
  {
    activityType: 'volleyball',
    key: 'volleyball_beach',
    nametr: 'Plaj Voleybolu',
    nameen: 'Beach Volleyball',
    metValue: 8.0,
    iconName: 'volleyball_beach',
    intensity: 'high',
  },
  // ── BOKS ──────────────────────────────────────────────────────────────────
  {
    activityType: 'boxing',
    key: 'boxing_bag',
    nametr: 'Torba Antrenmanı',
    nameen: 'Bag Work',
    metValue: 9.5,
    iconName: 'boxing_bag',
    intensity: 'high',
  },
  {
    activityType: 'boxing',
    key: 'boxing_sparring',
    nametr: 'Ring / Sparring',
    nameen: 'Sparring',
    metValue: 11.0,
    iconName: 'boxing_sparring',
    intensity: 'high',
  },
  {
    activityType: 'boxing',
    key: 'boxing_shadow',
    nametr: 'Gölge Boks',
    nameen: 'Shadow Boxing',
    metValue: 7.0,
    iconName: 'boxing_shadow',
    intensity: 'medium',
  },
  {
    activityType: 'boxing',
    key: 'boxing_kickbox',
    nametr: 'Kickboks',
    nameen: 'Kickboxing',
    metValue: 10.0,
    iconName: 'boxing_kickbox',
    intensity: 'high',
  },
  // ── YOGA ──────────────────────────────────────────────────────────────────
  {
    activityType: 'yoga',
    key: 'yoga_hatha',
    nametr: 'Hatha',
    nameen: 'Hatha',
    metValue: 2.5,
    iconName: 'yoga_hatha',
    intensity: 'low',
  },
  {
    activityType: 'yoga',
    key: 'yoga_vinyasa',
    nametr: 'Vinyasa Flow',
    nameen: 'Vinyasa Flow',
    metValue: 4.0,
    iconName: 'yoga_vinyasa',
    intensity: 'medium',
  },
  {
    activityType: 'yoga',
    key: 'yoga_yin',
    nametr: 'Yin Yoga',
    nameen: 'Yin Yoga',
    metValue: 2.0,
    iconName: 'yoga_yin',
    intensity: 'low',
  },
  {
    activityType: 'yoga',
    key: 'yoga_hot',
    nametr: 'Hot Yoga',
    nameen: 'Hot Yoga',
    metValue: 3.5,
    iconName: 'yoga_hot',
    intensity: 'medium',
  },
  {
    activityType: 'yoga',
    key: 'yoga_power',
    nametr: 'Güç Yogası',
    nameen: 'Power Yoga',
    metValue: 4.5,
    iconName: 'yoga_power',
    intensity: 'medium',
  },
  // ── PİLATES ───────────────────────────────────────────────────────────────
  {
    activityType: 'pilates',
    key: 'pilates_mat',
    nametr: 'Mat Pilates',
    nameen: 'Mat Pilates',
    metValue: 3.0,
    iconName: 'pilates_mat',
    intensity: 'medium',
  },
  {
    activityType: 'pilates',
    key: 'pilates_reformer',
    nametr: 'Reformer',
    nameen: 'Reformer',
    metValue: 4.0,
    iconName: 'pilates_reformer',
    intensity: 'medium',
  },
  {
    activityType: 'pilates',
    key: 'pilates_clinical',
    nametr: 'Klinik Pilates',
    nameen: 'Clinical Pilates',
    metValue: 3.5,
    iconName: 'pilates_clinical',
    intensity: 'medium',
  },
  // ── DANS ──────────────────────────────────────────────────────────────────
  {
    activityType: 'dance',
    key: 'dance_free',
    nametr: 'Serbest Dans',
    nameen: 'Free Dance',
    metValue: 5.0,
    iconName: 'dance_free',
    intensity: 'medium',
  },
  {
    activityType: 'dance',
    key: 'dance_salsa',
    nametr: 'Salsa / Latin',
    nameen: 'Salsa',
    metValue: 5.5,
    iconName: 'dance_salsa',
    intensity: 'medium',
  },
  {
    activityType: 'dance',
    key: 'dance_hiphop',
    nametr: 'Hip-Hop',
    nameen: 'Hip-Hop',
    metValue: 6.0,
    iconName: 'dance_hiphop',
    intensity: 'medium',
  },
  {
    activityType: 'dance',
    key: 'dance_zumba',
    nametr: 'Zumba',
    nameen: 'Zumba',
    metValue: 6.5,
    iconName: 'dance_zumba',
    intensity: 'medium',
  },
  {
    activityType: 'dance',
    key: 'dance_ballet',
    nametr: 'Bale',
    nameen: 'Ballet',
    metValue: 4.5,
    iconName: 'dance_ballet',
    intensity: 'medium',
  },
  // ── SAUNA ─────────────────────────────────────────────────────────────────
  {
    activityType: 'sauna',
    key: 'sauna_dry',
    nametr: 'Kuru Sauna',
    nameen: 'Dry Sauna',
    metValue: 1.5,
    iconName: 'sauna_dry',
    intensity: 'low',
  },
  {
    activityType: 'sauna',
    key: 'sauna_hamam',
    nametr: 'Hamam',
    nameen: 'Turkish Bath',
    metValue: 1.8,
    iconName: 'sauna_hamam',
    intensity: 'low',
  },
  {
    activityType: 'sauna',
    key: 'sauna_infrared',
    nametr: 'Infrared',
    nameen: 'Infrared Sauna',
    metValue: 1.5,
    iconName: 'sauna_infrared',
    intensity: 'low',
  },
  {
    activityType: 'sauna',
    key: 'sauna_steam',
    nametr: 'Buharlı',
    nameen: 'Steam Room',
    metValue: 1.5,
    iconName: 'sauna_steam',
    intensity: 'low',
  },
  // ── ŞOK HAVUZU ────────────────────────────────────────────────────────────
  {
    activityType: 'cold_pool',
    key: 'cold_icebath',
    nametr: 'Buz Banyosu',
    nameen: 'Ice Bath',
    metValue: 2.5,
    iconName: 'cold_icebath',
    intensity: 'high',
  },
  {
    activityType: 'cold_pool',
    key: 'cold_shower',
    nametr: 'Soğuk Duş',
    nameen: 'Cold Shower',
    metValue: 1.5,
    iconName: 'cold_shower',
    intensity: 'low',
  },
  {
    activityType: 'cold_pool',
    key: 'cold_contrast',
    nametr: 'Kontrast Terapi',
    nameen: 'Contrast Therapy',
    metValue: 2.0,
    iconName: 'cold_contrast',
    intensity: 'medium',
  },
  // ── GOLF ──────────────────────────────────────────────────────────────────
  {
    activityType: 'golf',
    key: 'golf_18holes',
    nametr: '18 Delik',
    nameen: '18 Holes',
    metValue: 5.5,
    iconName: 'golf_18holes',
    intensity: 'medium',
  },
  {
    activityType: 'golf',
    key: 'golf_9holes',
    nametr: '9 Delik',
    nameen: '9 Holes',
    metValue: 4.8,
    iconName: 'golf_9holes',
    intensity: 'medium',
  },
  {
    activityType: 'golf',
    key: 'golf_range',
    nametr: 'Atış Sahası',
    nameen: 'Driving Range',
    metValue: 3.5,
    iconName: 'golf_range',
    intensity: 'low',
  },
  // ── PADEL ─────────────────────────────────────────────────────────────────
  {
    activityType: 'padel',
    key: 'padel_match',
    nametr: 'Maç',
    nameen: 'Match',
    metValue: 7.0,
    iconName: 'padel_match',
    intensity: 'high',
  },
  {
    activityType: 'padel',
    key: 'padel_training',
    nametr: 'Antrenman',
    nameen: 'Training',
    metValue: 5.5,
    iconName: 'padel_training',
    intensity: 'medium',
  },
  // ── SU TOPU ───────────────────────────────────────────────────────────────
  {
    activityType: 'water_polo',
    key: 'waterpolo_match',
    nametr: 'Maç',
    nameen: 'Match',
    metValue: 11.0,
    iconName: 'waterpolo_match',
    intensity: 'high',
  },
  {
    activityType: 'water_polo',
    key: 'waterpolo_training',
    nametr: 'Antrenman',
    nameen: 'Training',
    metValue: 8.0,
    iconName: 'waterpolo_training',
    intensity: 'high',
  },
  // ── MASAJ ─────────────────────────────────────────────────────────────────
  {
    activityType: 'massage',
    key: 'massage_sports',
    nametr: 'Spor Masajı',
    nameen: 'Sports Massage',
    metValue: 1.2,
    iconName: 'massage_sports',
    intensity: 'low',
  },
  {
    activityType: 'massage',
    key: 'massage_relax',
    nametr: 'Relaksasyon',
    nameen: 'Relaxation',
    metValue: 1.0,
    iconName: 'massage_relax',
    intensity: 'low',
  },
  {
    activityType: 'massage',
    key: 'massage_deeptissue',
    nametr: 'Derin Doku',
    nameen: 'Deep Tissue',
    metValue: 1.2,
    iconName: 'massage_deeptissue',
    intensity: 'low',
  },
  // ── ESNEME ────────────────────────────────────────────────────────────────
  {
    activityType: 'stretching',
    key: 'stretching_static',
    nametr: 'Statik',
    nameen: 'Static Stretch',
    metValue: 2.0,
    iconName: 'stretching_static',
    intensity: 'low',
  },
  {
    activityType: 'stretching',
    key: 'stretching_dynamic',
    nametr: 'Dinamik Isınma',
    nameen: 'Dynamic Warmup',
    metValue: 3.0,
    iconName: 'stretching_dynamic',
    intensity: 'medium',
  },
  {
    activityType: 'stretching',
    key: 'stretching_foam',
    nametr: 'Foam Roller',
    nameen: 'Foam Rolling',
    metValue: 2.5,
    iconName: 'stretching_foam',
    intensity: 'low',
  },
  // ── DOĞA YÜRÜYÜŞÜ ─────────────────────────────────────────────────────────
  {
    activityType: 'hiking',
    key: 'hiking_easy',
    nametr: 'Kolay Patika',
    nameen: 'Easy Trail',
    metValue: 5.0,
    iconName: 'hiking_easy',
    intensity: 'medium',
  },
  {
    activityType: 'hiking',
    key: 'hiking_moderate',
    nametr: 'Orta Güçlük',
    nameen: 'Moderate Trail',
    metValue: 6.5,
    iconName: 'hiking_moderate',
    intensity: 'medium',
  },
  {
    activityType: 'hiking',
    key: 'hiking_hard',
    nametr: 'Zorlu Dağcılık',
    nameen: 'Hard Hike',
    metValue: 8.0,
    iconName: 'hiking_hard',
    intensity: 'high',
  },
  // ── MEDİTASYON ────────────────────────────────────────────────────────────
  {
    activityType: 'meditation',
    key: 'meditation_breathing',
    nametr: 'Nefes',
    nameen: 'Breathwork',
    metValue: 1.0,
    iconName: 'meditation_breathing',
    intensity: 'low',
  },
  {
    activityType: 'meditation',
    key: 'meditation_guided',
    nametr: 'Rehberli',
    nameen: 'Guided',
    metValue: 1.0,
    iconName: 'meditation_guided',
    intensity: 'low',
  },
  {
    activityType: 'meditation',
    key: 'meditation_mindfulness',
    nametr: 'Mindfulness',
    nameen: 'Mindfulness',
    metValue: 1.0,
    iconName: 'meditation_mindfulness',
    intensity: 'low',
  },
  // ── KÜREK ─────────────────────────────────────────────────────────────────
  {
    activityType: 'rowing',
    key: 'rowing_boat',
    nametr: 'Tekne',
    nameen: 'Boat Rowing',
    metValue: 7.0,
    iconName: 'rowing_boat',
    intensity: 'high',
  },
  {
    activityType: 'rowing',
    key: 'rowing_machine',
    nametr: 'Kürek Makinesi',
    nameen: 'Rowing Machine',
    metValue: 7.5,
    iconName: 'rowing_machine',
    intensity: 'high',
  },
  {
    activityType: 'rowing',
    key: 'rowing_canoe',
    nametr: 'Kano',
    nameen: 'Canoe',
    metValue: 5.0,
    iconName: 'rowing_canoe',
    intensity: 'medium',
  },
]

export async function POST() {
  let upserted = 0
  for (const item of SUBTYPES) {
    await db.activitySubType.upsert({
      where: { key: item.key },
      create: item,
      update: {
        nametr: item.nametr,
        nameen: item.nameen,
        metValue: item.metValue,
        iconName: item.iconName,
        intensity: item.intensity,
      },
    })
    upserted++
  }
  return NextResponse.json({ upserted, total: SUBTYPES.length })
}
